const { SlashCommandBuilder } = require("discord.js");
const utils = require("../../utils");

module.exports = {
  data: new SlashCommandBuilder()
    .setName("quote")
    .setDescription("Want to hear one of my CLASSIC lines?"),
  async execute(interaction) {
    await interaction.reply(quotes[utils.random.rand(quotes.length)-1]);
  },
};

const quotes = [
  `Welcome to the WORLD of TV TIME!!`,
  `Don't be blown away by the graphics, kids!`,
  `Kris! Only YOU may press any button to start!`,
  `At any time, you may press ONE button!`,
  `... you know what, forget it.`,
  `Now begin! Our state of the art... adventure!!!`,
  `It's cutting edge!!!`,
  `Behold... The door to... The physical challenge!!!`,
  `And so, our contestants' have spoken...`,
  `What may be their final words!!`,
  `Kids, cover your parents' eyes!!!`,
  `Because after this... There's no turning back!!!`,
  `You kidding?! We budgeted too much to not use this!!!`,
  `Mike, roll the tape!!!`,
  `This is it! Your final test!`,
  `Time for a physical challenge!!!`,
  `As a reward, a BONUS ZONE!!!`,
  `Hey hey!! We've got a budget!`,
  `Careful! Those cactuses are pointy!!!`,
  `Your prize awaits beyond these pots! If only you had a special skill!`,
  `Enemy!! Careful, brave heroes!!`,
  `Wow, absolutely spineless, folks!!`,
  `A rousing battle! Mike! Give them a free tube yogurt!`,
  `T: Welcome to DESERT! "Talk" to me for hints!\nS: Where's the "shut up" button?\nT: Sorry kid, that's premium!`,
  `That guy looks cute! You should save him!`,
  `10 years of fan mail are past this door!`,
  `Ready!? Mike, open up that door!!!`,
  `Ah.`,
  `There is no mail.`,
  `Mike... Get rid of that room. We don't need it.`,
  `We haven't gotten any mail. It's fine.`,
  `It's all fine, we don't need a mail guy.`,
  `GREAT performance, Elnina!`,
  `GREAT performance, Lanino!`,
  `Ralsei plush! Fill him with liquid, throw him against the wall!`,
  `I hope the class was paying attention to the physics of quicksand!`,
  `Hey kid, let's keep this show rolling!`,
  `Ooh, that's gotta hurt, folks!`,
  `Child's play!? I meant baby's work! This is bad, folks!`,
  `Another puzzle! Child's play for our heroes!`,
  `Puzzle two!! Get ready for a long one, folks!`,
  `Puzzle two!? Can they finish it within the episode!?`,
  `Whoops! Not that way!!!`,
  `Talk about a BLOCK head!!`,
  `Aww, it's beautiful folks!!!`,
  `This is getting awkward kid just push him`,
  `Okay, let's go to a commercial break!`,
  `What a great puzzle, folks!`,
  `You didn't want to see it. That's cool.`,
  `That's fine. Okay. Yeah.`,
  `You'll just never be able to see it again.`,
  `Incredible!!! You've discovered the SECRET MAILROOM!!!`,
  `Who left that there!!!`,
  `Who is that guy? Get him out of here!!`,
  `Enter the giant pyramid tile to enter!`,
  `Why is it small?`,
  `Maybe there's a smaller one inside?`,
  `You will never find the even smaller pyramid!`,
  `Quiz vortex! Watch out!`,
  `Solve the Quiz, get a Q!!!`,
  `Watch it! Falling rocks!`,
  `Watch it! Falling peaches!!`,
  `Uh oh! Watch out for falling peaches!!`,
  `I don't know where you got that idea.`,
  `I have no clue where you got that idea.`,
  `Don't worry, he's backstage with a controller just like everyone else!`,
  `NEED HEALING IN BATTLE? TRY OUR IN-GAME PURCHASES!`,
  `HEY THIEF! GET A KEY! JUST 250 POINTS!`,
  `BUY MORE LATER!!`,
  `THIEF!!`,
  `S: How do I kill this guy?\nT: Get in line, kid!`,
  `Are you crying for a buying!?`,
  `Then save up your points, folks!`,
  `POINTs can be exchanged for goods and services.`,
  `Uh oh! Weed alert!`,
  `You may find plucking these plants is "key"!`,
  `But you can't grip this grass without a "special treasure."`,
  `Can you find it somewhere on the board?`,
  `Guys. It's not in this room. It's in another room. Please.`,
  `Well, you somehow survived! Take a key!`,
  `Well, some of you survived! Take a key!`,
  `BINOCULARS. 10 POINTS TO TAKE A VIEW OF ATLANTIS STADIUM!`,
  `Trust me, it's a sight to behold!!!`,
  `YOU DON'T EVEN HAVE 10 POINTS!`,
  `ANOTHER pyramid!?`,
  `What? What? We have a budget to keep in mind you know!!!`,
  `H-HEY!!`,
  `HEY!!`,
  `Wait! That's *MYsecret bonus zone!`,
  `Well, haha, good luck reaching those!`,
  `I keep my investments SHORT-proof!`,
  `W-wait!`,
  `I... I'm covered in ill-gotten gains!`,
  `He told me digital currency was SECURE!!!`,
  `Sigh... Can't a guy have just one bonus zone to himself...? `,
  `That's right Ralsei!! Honesty and kindness pay!!!`,
  `Here, have a single point!!!`,
  `Hey hey hey what happened to respecting my zone!?!?`,
  `Atlantis sure is beautiful this time of year!`,
  `A cracked wall! What could it mean!?`,
  `I'm back! I apologize to the viewers!!!`,
  `Nothing here! Head up to find a DOCK!`,
  `Ha ha, what's UP... DOCK!?`,
  `Okay, head north or I'll DOCK your points!`,
  `Well done Susie!!`,
  `You're really getting a kick out of this, huh?!`,
  `Nothing! Ignore that! It's just a leftover!`,
  `Huh? I mean... uh... it's unfinished!`,
  `Nothing! It just goes back to...`,
  `It doesn't matter! Let's get back to the game!`,
  `Those are no ordinary blocks! This room presents a challenge!`,
  `See? He gets it!`,
  `So uh... the Tropic of Love...`,
  `Anyone else think that was cool? Haha...`,
  `Anyone?`,
  `Sorry, nothing up this way, folks!`,
  `See, it just loops!`,
  `This part's unfinished! Go back!`,
  `Unfinished! UNFINISHED, I said!`,
  `MIKE, CUT! CUT!!!`,
  `Phew! Sorry folks, our contestants got a little lost!`,
  `Welcome to KODAKODA ISLAND!`,
  `Sorry, the "grey" spring is blocked up.`,
  `Oh no! the green spring is blocked up!`,
  `I'm BACK! Onto ATLANTIS!`,
  `... why is this RAINBOW so IMPURE!?`,
  `You know what that means, kids!!!`,
  `Nevermind, folks!`,
  `Still only one lover!`,
  `YOU CAN'T USE KRIS AND RALSEI!!`,
  `RALSEI DOESN'T COUNT!!!`,
  `KRIS DOESN'T COUNT!!!`,
  `What!? The trees are green! Green!!!`,
  `Alright, this is it folks!`,
  `Come out, you two!`,
  `Alright, open your eyes!`,
  `Wow, looks like your game characters are just about to meet...`,
  `... At Lover's Peak!!!`,
  `Oops! Duty calls! Gotta go, kids!`,
  `(I'll give them a little alone time...)`,
  `Watch out! Snipers! Kris, they're aiming only for you!`,
  `Kris!! Duck and cover!!`,
  `Hey kids, wrong way!`,
  `Oh, go back! You missed the special prize!`,
  `COME ON IN! THIS FRESH AND FRUITY JAMBOREE WILL HEAL YOUR HP!`,
  `... HEY, you two aren't supposed to be here!`,
  `Who said you could do that on the job!?`,
  `Who the heck was that?`,
  `Oh! It's MAGIC RAFT!`,
  `You've unlocked a NEW RAFT!!!`,
  `With the MAGIC RAFT, the OCEAN is your OYSTER!`,
  `Perhaps you need a secret tool...`,
  `RAFT forth! UNKNOWN MYSTERIES await you!`,
  `PHEW! FINALLY, SOME PEACE AND QUIET!`,
  `... I WONDER… IF THEY EVEN LIKE THE GAME...?`,
  `I'M TRYING MY BEST TO MAKE IT FUN, BUT...`,
  `HERE AND THERE, STRANGE THINGS ARE SHOWING THROUGH...`,
  `OH, WHY DID I BASE IT OFF THIS STUPID OLD THING!!`,
  `... KRIS, OH, KRIS IF YOU COULD JUST SMILE... LAUGH...`,
  `TELL ME I'M DOING SOMETHING RIGHT... PLEASE...`,
  `WHAT THE? I HEAR FOOTSTEPS!`,
  `NO GOOD I NEED TO MAKE MY GETAWAY`,
  `Heh, I think I know where we're going.`,
  `Two!? Not with this union breathing down my neck!`,
  `Yeah, this is where you're supposed to go.`,
  `The end is close! Back to LOVER'S PEAK!`,
  `Congrats kids, you've earned it!`,
  `... Wait a second... Your controllers are...`,
  `Huh? My antennas are...`,
  `Sorry, be right back, kids!`,
  `Sorry kids, no falling rocks today.`,
  `Sorry kids, no falling peaches. They expired.`,
  `Those also expired.`,
  `Even I don't know what's this way!`,
  `And there's the DOOR, folks! They're at the ROOF!!`,
  `THE MOONCLOUD KEY CARD WAS USED.`,
  `The contestants, WOW! They have the ELEVATOR KEY CARD!`,
  `Alright, controllers all clean!?`,
  `Everyone back to the couch, let's finish up Board 3!`,
  `Mike, turn on the power.`,
  `Haha, that's strange! Usually it goes right on!`,
  `Mike, can we, uh, haha, try that again?`,
  `That's funny.`,
  `No one's there.`,
  `The characters... they're gone.`,
  `Umm...`,
  `...`,
  `Watch out! Falling rocks!`,
  `The SHRINE is ASHINE! What could it mean!?`,
  `THE ELEVATOR IS LOCKED WITH THE MOONCLOUD KEY CARD.`,
  `Oh no! Looks like you need the key card first.`,
  `But don't worry... You can take the stairs!`,
  `Board 2 is now ready!!`,
  `All performers and contestants report to the STAGE immediately!!`,
  `Ouch! Don't touch the cactuses!`,
  `Don't touch the cactuses!`,
  `They're very fragile and expensive!`,
  `... HOW DID THINGS TURN OUT LIKE THIS...`,
  `... KEEPING POOR TORIEL ALL LOCKED UP...`,
  `IF ONLY HE HADN'T ABANDONED ME.`,
  `MY OLD PARTNER...`,
  `I WAS GONNA PUT HIM ON TV! MAKE HIM A STAR!`,
  `I GAVE HIM EVERYTHING! EVERYTHING I HAD! MY LIFE ADVICE!`,
  `ALL. HE HAD. TO DO. WAS TELL ME WHAT HIS LITTLE SECRET WAS.`,
  `HIS SECRET TO BEING A BIG SHOT...`,
  `IT TOOK A LITTLE SWEET TALK...`,
  `BUT JUST WHEN I HAD, FINALLY, FINALLY ? HA HA --`,
  `GOTTEN HIM TO SIGN THE DEAL.`,
  `HE SUDDENLY HAD TO TAKE A PHONE CALL.`,
  `BUT WHEN HE PICKED IT UP, HIS FACE TURNED PALE...`,
  `AND HE RAN RIGHT OUT OF THE ROOM WITH THE RECEIVER HANGING!`,
  `SO I WENT TO PICK IT UP...`,
  `THINKING IT WAS FINALLY MY CHANCE TO BE A BIG SHOT.`,
  `... BUT THERE WAS NOBODY THERE!`,
  `THAT LITTLE FREAK RIPPED ME OFF!`,
  `... I WISH THEY NEVER BROUGHT THAT LAPTOP HOME...`,
  `K... KRIS! KRIS, I DIDN'T SEE YOU THERE!`,
  `I... I DID WHAT YOU SAID, KRIS! HA... JUST LIKE OUR DEAL!`,
  `Y-YOU AREN'T GONNA TURN ME OFF AGAIN, ARE YOU...?`,
  `WHIFF... WHIFF... MY NOSE KNOWS YOU DIDN'T DO THE OTHER QUIZZES.`,
  `GO HIT THE BEACH AND SNIFF THEM OUT!`,
  `ACHOO! ACHOO! MY NOSE KNOWS YOU FOUND THE OTHER QUIZZES.`,
  `NOW THERE'S JUST ONE LAST QUESTION...`,
  `DO YOU WANT THESE POINTS, OR NOT!?`,
  `...`,
  `AND THAT'S THE FINAL QUIZ!`,
  `IN A WAY, WE WERE ALL WINNERS...`,
  `SO IF YOU DON'T MIND,`,
  `I'LL BE TAKING THAT ALL-EXPENSES-PAID TROPICAL VACATION!`,
  `What!? My beeper!? Zapper got stuck again!? Darnit!`,
  `I have to go. Don't have too much fun without me!`,
  `Now begin! Our state of the art... Modern electronic video adventure!!!`,
  `It's cutting edge!!!`,
  `Umm, can I finish reading the MANUAL?`,
  `No! For your adventure awaits...`,
  `Just down that hole!!!`,
  `The secret lawnmower game! Everybody's favorite!`,
  `Push the lawnmower and it will fly! The grass will grow as you mow!`,
  `Cut as much grass as you can before the timer runs out to get some points!!!`,
  `Sure, yeah. I was done. Go ahead.`,
  `When you're ready, push the lawn mower to start!`,
  `A score of 1500?! IMPRESSIVE!`,
  `A BOSS!? ME!? I'm offended!!!`,
  `HEY!!! THAT'S CROISSANT MISUSE!!!`,
  `HEY FOLKS! IT'S SPHINX-TENNA!`,
  `ANSWER MY RIDDLE AND I'LL GIVE YOU ONE KEY!`,
  `... IS WHAT I WOULD SAY, BUT, YA SEE, IT'S A BIT EMBARRASSING...`,
  `SEE, I'M MISSING MY Q'S! BRING TWO OF 'EM HERE AND I'LL QUIZ YA!`,
  `I'M MISSING MY Q'S! BRING TWO OF 'EM HERE AND I'LL QUIZ YA!`,
  `MY NOSE IS THE ONLY NOSE THAT KNOWS.`,
  `DON'T TRY TO USE THE LONG NOSE OF ANY OTHER SUSPICIOUS CHARACTER!`,
  `NOSE-PICKING, ER, LOCK-PICKING IS NOT ALLOWED!`,
  `WOW, YOU GOT TWO Q'S JUST FOR ME!?`,
  `OH, OH, THAT'S MUCH BETTER!`,
  `NOW THAT I'M DRESSED...`,
  `IT'S A QUIZ TO THE DEATH!`,
  `WELL DONE. FOR YOU THAT KNOWS, A NOSE!`,
  `YOU DIDN'T EVEN KNOW THAT!?`,
  `HA HA HA HA -- OH NO, MY NOSE FELL ASLEEP!`,
  `I HOPE THAT YOU HAVE A NICE DAY.`,
  `WELCOME TO THE BOARD GAME GAME BOARD!`,
  `TO WIN THE GAME, ENTER THE PYRAMID AND FACE THE FINAL CHALLENGE.`,
  `YOU FOUND THE KEYS FOLKS! APPLAUSE SIGNS, APPLAUSE SIGNS!`,
  `WHAT!? YOU ALREADY FOUND EVERYTHING!?`,
  `THAT WAS FAST... HA, HA. YOU DESERVE APPLAUSE FOR THAT ONE!`,
  `L-look everyone!! It'll be fine!! I'm cutting edge!! I'm new!! I'm TV!!!`,
  `Three-colors, cathode raytube!! Make you laugh, make you cry!!`,
  `Entertainment that never gets old!!`,
  `H-hey, stop!! Don't go...!!`,
  `Darnit, this is all that little spammy MAILMAN'S fault!!`,
  `He... he told me he was gonna teach me how to use technology!!`,
  `H... How to plug in and make! It! BIG...!`,
  `And where is HE!?`,
  `Arrrgh, if I could get my hands on...`,
  `Wait, where are you going!?`,
  `Stop!! Help me!! Help!!`,
  `Does anyone know what an e-mail is???`,
  `Elnina!! Lanino!? You two!? C'mon, old friends, you can't leave...!`,
  `Fine!! Fine, you wanna go, GO!!`,
  `We'll see how far the Lightners get...`,
  `WITHOUT THE WEATHER CHANNEL!! HAHAHA!`,
  `How can they know the Weather without TV!?!? Hahahaha!!`,
  `What? Apps? What... What are those!? Everything's changing so fast...`,
  `M... Mike? Mike, you... you're leaving, too!?`,
  `MIKE!! NO!! ANYONE BUT YOU!! ANYONE!!`,
  `Look! There, I can see it...!`,
  `There's the Dark Fountain! If we can just...`,
  `No!! NO!! NO!!!!`,
  `WHAT are you doing!? WHERE are you going!? Ahaha!!`,
  `There are still GAMES to play!! SHOWS to watch!!`,
  `Laughs and SCREAMS!! Smiles and TEARS!!`,
  `Just wander back to your seats and we can...`,
  `ENOUGH of your dumb games!!`,
  `Why the hell do you want us to play so bad anyway!?`,
  `Kris.`,
  `Kris knows why.`,
  `Do you remember it, Kris?`,
  `When everyone came over for the holidays?`,
  `Back when I was just a little old TV.`,
  `Everyone used to gather around my glow to watch the specials,`,
  `Smiling. Laughing. Eating butterscotch pie.`,
  `Wasn't that just so much... fun?`,
  `To watch me.`,
  `I... was so happy.`,
  `Then...`,
  `People stopped coming.`,
  `Everyone disappeared... one by one...`,
  `No one wanted to watch TV anymore.`,
  `No one wanted to play games anymore.`,
  `I've been all alone...`,
  `Until now.`,
  `When the KNIGHT appeared...`,
  `The ROARING KNIGHT.`,
  `And I was told that if I keep you three busy,`,
  `I can have ALL the people watch me that I want.`,
  `And, I've been having SO much fun playing with you all,`,
  `I... just don't want it to end!`,
  `So... please... just say it with me.`,
  `Wh-what are you doing!? I just had this suit DE-AXED!!!`,
  `Alright. I get it.`,
  `I. GET IT! I REALLY get it!!`,
  `Talking!! I've been doing too much... TALKING!!`,
  `NO MORE questions!! What you need...`,
  `Is another <:physchal1:1445906261001637970><:physchal2:1445906262591275058><:physchal3:1445906263937646756><:physchal4:1445906265552457728><:physchal5:1445906266299039867><:physchal6:1445906267737423983>!!`,
  `What <:lovely1:1444089294154109049><:lovely2:1444089295521710231> contestants we've got TODAY, folks---!!!  `,
  `YES!!! You three are the <:stars1:1445470913641316502><:stars2:1445470915356917881><:stars3:1445470916992569494> of today's SHOW!!!`,
  `Mr. Tenna's Marvelous Mystery Board...`,
  `<:show1:1445469367654416435><:show2:1445469370494222549><:show3:1445469372884979764>!!!`,
  `What am I doing? You should be wondering what YOU'RE doing!`,
  `You're about to play the greatest game of YOUR life!`,
  `Answer CRAZY QUESTIONS!! Pass PHYSICAL CHALLENGES...`,
  `And you'll all win some TV-Tastic <:prizes1:1446548515718430831><:prizes2:1446548516884316362><:prizes3:1446548517693817014><:prizes4:1446548518629015623>!!!`,
  `FLORAL COWBOY BATH CURTAINS!!! `,
  `A BRAND NEW FAMILY CAR!!! `,
  `BIG BRO'S TALKER-BACKER!! `,
  `KITCHEN SINK FUR-GUARD!! `,
  `CHOCOLATE CHEWY ROLL-UM'S!!! `,
  `A GENUINE RALSEI PLUSH!! `,
  `AND THAT'S!`,
  `NOT!`,
  `ALL!`,
  `Hey Doctor Tennaville! What's today's prescription?`,
  `Why, it looks like a prescription for... ONE <:grandprize1:1446237435007733841><:grandprize2:1446237435481686198><:grandprize3:1446237437515923476><:grandprize4:1446237438589796455><:grandprize5:1446237439747297462><:grandprize6:1446237440523239495>!?`,
  `That's right! Today's <:grandprize1:1446237435007733841><:grandprize2:1446237435481686198><:grandprize3:1446237437515923476><:grandprize4:1446237438589796455><:grandprize5:1446237439747297462><:grandprize6:1446237440523239495> is this season's MOST popular item...`,
  `Encased in our patented MYSTERY BALL...`,
  `This Dark World's ONE AND GREATEST TREASURE!`,
  `Hey, bet you wanna know what's INSIDE, don't ya, folks!?`,
  `Well, great news, CADOOS and CADETTES! EVERYTHING can be YOURS!`,
  `All you have to do is...`,
  `<:bigwin1:1446551898390925412><:bigwin2:1446551899477377115>`,
  `WOW!!! I've never seen the <:funometer1:1446242625886748802><:funometer2:1446242628684353733><:funometer3:1446242629615616275><:funometer4:1446242631175635005><:funometer5:1446242632677199903> like THIS, folks!!!`,
  `Now don't touch that DIAL, because TONIGHT, WE are gonna have one HECK of a...`,
  `Well, uh... this is a GAME SHOW, and you guys are the CONTESTANTs... right?`,
  `You... you aren't?`,
  `Oh. Well, uh... that's just...`,
  `That's just hunky-doody, y'know! You do YOU! Meanwhile, I, uh...`,
  `Guess it'll just be... me and the logo! Ha.`,
  `You... you'll give it a shot? My game?`,
  `Oh, you WILL!?!? Oh, you THRILL!?`,
  `Mike!! The lights!! The sounds!! The whatzits!! The doo-zits!!`,
  `Turn 'em all on!!`,
  `-# _(And get me a cup of coffee)_`,
  `Right over here, ladies and germs!!`,
  `Would everyone please give a warm welcome...`,
  `To today's <:star1:1446248419545845872><:star2:1446248420871372821><:star3:1446248421726879854> contestants!!!`,
  `Everyone! Please cheer their <:names1:1445920123834732585><:names2:1445920124942028920><:names3:1445920125784948807><:names4:1445920126372151348>!`,
  `Oh, right.`,
  `CONTESTANTS!!!`,
  `Your <:names1:1445920123834732585><:names2:1445920124942028920><:names3:1445920125784948807><:names4:1445920126372151348> please!!!`,
  `Alright! Now, for the introductions!!!`,
  `First up, prince-from-the-dark and three time accidental fluffiest pet contest winner!`,
  `RAL-sei!!!`,
  `Next up, Kris's friend, monster maniac, and WHERE did you wreck those pants?`,
  `SUSIE!!!`,
  `Hey folks, looks like the censors ARE gonna kill me!`,
  `Only on THIS show because they weren't blue enough for "The Sblurfs"...`,
  `Kris!!!`,
  `Well, don't "Kri" until the ending, folks!`,
  `"KRS"? I told you! No KuRSing or the censors will kill me!`,
  `Well, this is gonna get confusing, isn't it, folks!?`,
  `AAA!? They're already SCREAMING from DELIGHT, folks!!!`,
  `Hey, hopefully someday you can learn how to spell your own name, too!`,
  `Now that we've all been (im)properly introduced...`,
  `MIKE, the <:board1:1445921047496101952><:board2:1445921048737484990>, please!`,
  `Today's "GAME" SHOW will be... A VIRTUAL ADVENTURE through TV DESERT!`,
  `Each of you will use our CUTTING EDGE, PROPRIETARY CONTROLLER PADS...`,
  `To control FANTASY VERSIONS OF YOURSELF in a world so REAL, you'll forget IT'S NOT!`,
  `On your QUEST you will fight BATTLES... quiz <:quizzes1:1443452224780111872><:quizzes2:1443452225593675819><:quizzes3:1443452226461896868>... gain POINTs...`,
  `And maybe learn to <:love1:1443452223387340984><:love2:1443452224029065276> each other a little along the way.`,
  `Now, don't TOUCH THAT DIAL, and don't STOP THOSE SMILES!! Because...`,
  `<:tvtime1:1445136405633175672><:tvtime2:1445136406455517374><:tvtime3:1445137403399508119><:tvtime4:1445136410582585344><:tvtime5:1445136411572310137>`,
  `Hon hon!! Cool your burners, folks!!`,
  `Today's <:physchal1:1445906261001637970><:physchal2:1445906262591275058><:physchal3:1445906263937646756><:physchal4:1445906265552457728><:physchal5:1445906266299039867><:physchal6:1445906267737423983>...`,
  `Is the COOKING CHANNEL!`,
  `Kris, your mother used to <:love1:1443452223387340984><:love2:1443452224029065276> cooking shows, didn't she?`,
  `Oh, how she'd LAUGH, glowingly, along with each new recipe,`,
  `Feverishly taking notes on each step to make them for her family...`,
  `As you and your <:brother1:1446249794652737649><:brother2:1446249795713896478><:brother3:1446249797014257696><:brother4:1446249797878022175> pretended the chefs were bungling the simplest parts!`,
  `"Darn!! I overcooked the water!!"`,
  `"Oops!! No!! I keep breaking the eggs!! Oops!!"`,
  `AHAHAHA!! Hahaha!! That sure was <:fun1:1444090417078341723><:fun2:1444090418127048734>, wasn't it?`,
  `Now, are you ready or what!?`,
  `Here are the instructions for the <:challenge1:1445924102388056256><:challenge2:1445924103201624094><:challenge3:1445924104187412571><:challenge4:1445924105051308192><:challenge5:1445924106569777173>.`,
  `FOOD is FALLING! KRIS, CATCH the food on your head to STACK IT UP!`,
  `THROW it to customers with (button)! If the food touches them, they'll gobble it up!`,
  `SPECIAL CUSTOMERS will sometimes appear! They're worth <:big1:1446252285629042871><:big2:1446252286681551002> POINTs, don't miss 'em!`,
  `SUSIE will probably cook BURNING FIRE. JUMP over it with (button)!`,
  `Missed food will also turn into BURNING FIRE, so be careful!`,
  `Big stack, <:big1:1446252285629042871><:big2:1446252286681551002> POINTs! But... You'll MOVE and JUMP slower! Be careful!`,
  `Last until the end to <:win1:1446551900206923876><:win2:1446551901314220062><:win3:1446551902262263818> But if the POPULARITY GAUGE runs out, it's GAME OVER!`,
  `Now don't touch that dial, OR that fire!`,
  `Because...`,
  `<:tvtime1:1445136405633175672><:tvtime2:1445136406455517374><:tvtime3:1445137403399508119><:tvtime4:1445136410582585344><:tvtime5:1445136411572310137>`,
  `THAT's what I like to hear!`,
  `Now get those pans over easy, or these eggs are gonna be TOUGH!`,
  `STOP! STOP! <:stop:1443407391394758667>!!!`,
  `It CAN'T be over already!! NO!!`,
  `The <:funometer1:1446242625886748802><:funometer2:1446242628684353733><:funometer3:1446242629615616275><:funometer4:1446242631175635005><:funometer5:1446242632677199903>'s still only at 80%!!`,
  `Ah, you see...`,
  `That was just...`,
  `... <:round11:1446243610931630311><:round12:1446243612106166474><:round13:1446243614933123312>`,
  `Of course!! There's 2 <:rounds1:1446247679096131584><:rounds2:1446247680794824814><:rounds3:1446247681855852726>!! 2!!`,
  `You haven't ever heard of a game show with just ONE <:round1:1446246250134376681><:round2:1446246251313238217>, have you!?`,
  `Exactly!! It's preposterous!! Outrageous!! It'd be bad TV!!`,
  `-# _(And trust me. I know TV)_`,
  `Great!! And no!! And now, a <:word1:1446253276063334472><:word2:1446253278315675790><:word3:1446253280249249873> from our sponsors!!`,
  `WELCOME back, everyone, to the show that'll make you SCREAM at your SCREEN,`,
  `<:show1:1445469367654416435><:show2:1445469370494222549><:show3:1445469372884979764>!!`,
  `Today's episode is brought to you by our sponsor...`,
  `The gushing pillar of darkness that gives us all form -<:darkfountain1:1446241026800091179><:darkfountain2:1446241027626111006><:darkfountain3:1446241028443996334><:darkfountain4:1446241029404754213><:darkfountain5:1446241030444683429><:darkfountain6:1446241031304511568>!!`,
  `Now available in unsettling obsidian and pulsating rainbow!`,
  `Now, MIKE, the <:board1:1445921047496101952><:board2:1445921048737484990>, please!`,
  `Slather on that sunscreen, everyone! Because...`,
  `Today's second - and FINAL - board will be an aquatic adventure to a desert island!`,
  `That's right -- an all-expenses paid trip to a beautiful tropical paradise!!`,
  `Haha! Wish I could go but I'm just a big electric box attached to the wall!! Haha!!`,
  `-# _(Though I would look good with a tan.)_`,
  `For this BOARD's GOAL, you'll be aiming to enter the floating ATLANTIS STADIUM!`,
  `Legend has it, the best way there is our super high budget RAINBOW BRIDGE!`,
  `However, the RAINBOW only appears if TWO <:lovers1:1445919280549068852><:lovers2:1445919281580871744><:lovers3:1445919282709139516><:lovers4:1445919283514314902> meet at LOVER'S CLIFF!`,
  `By the way, don't forget to take lots of PHOTOS while you're on vacation!`,
  `Now, we're gonna have some real fun in the sun today, SO DON'T TOUCH THAT DIAL!`,
  `-# _(Well, okay, you can touch it. Just be gentle.)_`,
  `Now, without further ado...`,
  `<:tvtime1:1445136405633175672><:tvtime2:1445136406455517374><:tvtime3:1445137403399508119><:tvtime4:1445136410582585344><:tvtime5:1445136411572310137>`,
  `That's right! Get out your lighters for the LIGHTNERS, ladies and germs!`,
  `Because it's time for a crashing, banging, booming, crooning...`,
  `<:rock1:1446242018798993448><:rock2:1446242019704963103><:rock3:1446242020656939050><:rock4:1446242021881938010><:rock5:1446242022737318055>!!!`,
  `Oh, Kris! Remember DECEMBER? Oh, that little musical prodigy...`,
  `Remember when she'd grab the remote and swap it from cartoons...`,
  `... to that WILD music video channel Toriel FORBID you to see?`,
  `-# _(Guess your mother's never been a fan of alligators in bikinis)_`,
  `Dess, rocking her guitar and singing along with those nasty, nasty songs!`,
  `Didn't you all think she was just so... COOL?`,
  `HECK! Maybe you could get her to come back and watch again sometime!?`,
  `No worries! It's so SIMPLE, a FAX MACHINE could do it!`,
  `When the MUSIC starts, notes will flow from the top like HONEY.`,
  `When the NOTES hit the MARK, press with good timing to PLAY them!`,
  `[Z] (or [Left]) will play notes on the LEFT!`,
  `[X] (or [Right]) will play notes on the RIGHT!`,
  `Make sure to HOLD the button for those LONG NOTES!`,
  `Got it, Kris?! Good! That's all you gotta know!`,
  `SUSIE and RALSEI will be doing their own things, so IGNORE THEIR PARTS.`,
  `That being said, MUSIC is a TEAM SPORT! If ANY of you play bad...`,
  `The POPU & LARITY LIGHTS will darken! And if they go black...`,
  `It's LIGHTS OUT!!!`,
  `NOW, how about a SOUND CHECK!? This one's just for practice!`,
  `ALRIGHT! SOUND: Checked! DRUMS: Loud! BOYS: Fluffy!`,
  `RALSEI! Got those lyrics ready!?`,
  `TOO BAD! NOW, AUDIENCE! Give it up one last time...`,
  `<:tvtime1:1445136405633175672><:tvtime2:1445136406455517374><:tvtime3:1445137403399508119><:tvtime4:1445136410582585344><:tvtime5:1445136411572310137>`,
  `Wow, folks! Looks like they've reached the end of our FINAL <:board1:1445921047496101952><:board2:1445921048737484990>!`,
  `It's sad to say goodbye, but when you gotta go... you gotta go!`,
  `MIKE, roll the credits...!`,
  `STOP!!! <:breaking1:1446597036601507840><:breaking2:1446597037486375113><:breaking3:1446597038639681628><:breaking4:1446597046290350151><:breaking5:1446597047615754280>!`,
  `Due to your SPEED, viewer donations have been POURING IN...`,
  `And we have met the SPECIAL INCENTIVE!`,
  `YES! The <:funometer1:1446242625886748802><:funometer2:1446242628684353733><:funometer3:1446242629615616275><:funometer4:1446242631175635005><:funometer5:1446242632677199903> doesn't lie! The viewers' voices are in...!`,
  `You've qualified for...`,
  `The <:bonusround1:1446246242924630098><:bonusround2:1446246243952234596><:bonusround3:1446246244895949031><:bonusround4:1446246248016379935><:bonusround5:1446246249002172466>!!!`,
  `Pass? P... Pass?`,
  `You mean... STOP PLAYING!?`,
  `Well... I mean... If you want to!`,
  `I mean, it was just gonna be a special board, but... alright!`,
  `Mike! Tear down the board! Tear down the set!`,
  `Tear down my house!! Tear down my kids!!`,
  `Audience... you're gonna have to go home!`,
  `Please... (sniff) make sure to check out our gift shop (sniff)...`,
  `(sniff) It's got... (sniff) funny whirligigs...`,
  `(sniff) ... you'll play?`,
  `MARVELOUS!!! Mike, rebuild the set!! Rebuild my kids!!`,
  `We are gonna have a GREAT show for you folks!! The best ever!!`,
  `No!! And now a WORM from our sponsors!!!`,
  `Oh <:toriel1:1446254466029322322><:toriel2:1446254467107389440><:toriel3:1446254467862368286>...!`,
  `Phew! There you are, still sleeping like a little angel!`,
  `Haha! Who the HECK knows what I'D do if you woke up!`,
  `...`,
  `I'm sorry we gotta do this to you, Tori...`,
  `You were the last one to really... give me a good look, back then.`,
  `But hey, that's show business! Nothing... stays big forever.`,
  `Without... a little HELP, that is.`,
  `That's why you're gonna be our little TRUMP CARD...`,
  `Heheheh...`,
  `Hahahahahaha-`,
  `...`,
  `...`,
  `Umm...`,
  `K... Kris! Hey, Kris! Kris ol' buddy, ol' pal! How's it going!`,
  `It's uh, it's uh, it's goin' great, isn't it!? Everything's, just hunky doody!`,
  `Haha... Uh, heheh... Where are your, uh, buddies? Your pals?`,
  `By yourself, huh? Don't you wanna, y'know, heheh, keep 'em company? Heheh...`,
  `Oh, uh, hey, would you look at that! My, uh, my beeper's going!`,
  `You know, my silent beeper! Haha, it's a new one! I... I gotta be goin' now!`,
  `By the way... Seen your father recently? Your brother?`,
  `You know, we still got that cowboy program... The one your dad likes...`,
  `He was, heh, bouncin' you on your knee as you watched it together...`,
  `Sorry, Kris! Sorry! I gotta...`,
  `I have to go!`,
  `Welcome to EXTRA GAME! Tonight, our <:physchal1:1445906261001637970><:physchal2:1445906262591275058><:physchal3:1445906263937646756><:physchal4:1445906265552457728><:physchal5:1445906266299039867><:physchal6:1445906267737423983> will be...`,
  `W-Wait just a moment!! I'm receiving an EMERGENCY BROADCAST...`,
  `Something MASSIVE has begun ASSAULTING the CITY!!!`,
  `Multiple buildings are up in <:flames1:1446255797008072845><:flames2:1446255798677143773><:flames3:1446255799746953317><:flames4:1446255800745070603>!!!`,
  `At this rate... everything... EVERYONE will be destroyed!!!`,
  `Can anyone PLEASE tell me who this MONSTER IS!?`,
  `...`,
  `That's right!!! It's a giant monster movie!!! Starring Susie!!!`,
  `RIGHT! <:susiezilla1:1445911388022247606><:susiezilla2:1445911388827553852><:susiezilla3:1445911390010216488><:susiezilla4:1445911391977607300> will be our baddie smashing, hyper spinning star of the day!`,
  `Ms. Zilla!! You were watching the monster marathon until you fell asleep.`,
  `I was so HAPPY to see someone so excited to tune in!!!`,
  `So this final event's a <:special1:1446255286301102352><:special2:1446255289832833078> SERVICE just for you!!`,
  `And haha, by all means, please! Come over to Kris's and watch MORE TV ANYTIME!`,
  `You don't even have to come in! Stand outside and watch me through the window!`,
  `I won't tell anyone!! The police will never know!! Promise!! Hahaha!!`,
  `No. Uhh, no. <:susiezilla1:1445911388022247606><:susiezilla2:1445911388827553852><:susiezilla3:1445911390010216488><:susiezilla4:1445911391977607300> had a change in her TV-loving heart.`,
  `She may wreck the city, but she'll protect me, TV statue, with her life.`,
  `For if the bad guys take me down... There's no more TV!!!`,
  `Now, the rules are simple!`,
  `Haters of true entertainment are constantly trying to kill me!`,
  `Defeat them before they hit me and ruin my pristine sheen!`,
  `Susie's ok to get hit, but if I run out of "Popularity", it's game over!`,
  `Kris and Ralsei control Susie via rope like an unwanted puppet.`,
  `Spin the rope with [Z] to smash anything and everything.`,
  `That's it! You'll learn the rest on the job... Or else!`,
  `Now, all READY!? Tail on tight!? Taken your radioactive breath mints!?`,
  `WELCOME BACK to another ELECTRIFYING episode of TV TIME!`,
  `Today's board will take place in beautiful TV CITY...`,
  `-# _(But don't ask why the car don't have feet!)_`,
  `Collect two Q's from each corner of the CITY, and...`,
  `Game... over?`,
  `... Old.`,
  `No, haha! Ralsei, RALSEI! Buddy-BOY! It's fine! I GET IT! Look, I get it!`,
  `CLASSIC TV... sometimes just takes a little TIME to APPRECIATE!`,
  `So how about this?`,
  `We'll all do ONE MORE LITTLE GAME...`,
  `One last ENCORE!`,
  `And this time, we'll play`,
  `Until you LIKE IT.`,
  `<:gameover1:1446550745838125087><:gameover2:1446550746748162180><:gameover3:1446550747503136879><:gameover4:1446550748564426812><:gameover5:1446550749873180823>`,
  `THE <:game1:1446549631550099476><:game2:1446549632841945301>'S never <:over1:1446550144798556160><:over2:1446550145805062214>!!!`,
  `And if YOU don't wanna play anymore...`,
  `It's time for ME to TAKE CONTROL!!!`,
  `MIKE, crank it all up to MAX!!!`,
  `<:tvtime1:1445136405633175672><:tvtime2:1445136406455517374><:tvtime3:1445137403399508119><:tvtime4:1445136410582585344><:tvtime5:1445136411572310137>`,
  `Now it's my turn to play!!!`,
  `Hey, isn't this fun!?`,
  `I'm not broken! I don't have burn-in! I'm... fun!!!`,
  `C'mon, say it!!! I'm!!! Fun!!!`,
  `... Fine. You don't wanna say it?`,
  `Maybe a quiz will help you answer!!!`,
  `PHEW! WHAT a challenge, folks!`,
  `Now, is it me or does everyone look a little SLEEPY!?`,
  `C'mon, SUSIE! What happened to our late-night TV marathon!?`,
  `Let's wake up those noggins with a little QUIZ!!!`,
  `Hey, so, uh... what the HECK was that?`,
  `Haha, I'm with YOU guys! That was WEIRD!`,
  `Let's get back to normal!`,
  `How did you like my "MARATHON!?" Hahaha!!`,
  `...........`,
  `Well don't everyone say what they think at once!!! Hahaha!`,
  `Just kidding. You WILL.`,
  `Wasn't that quiz just oodles of fun, folks!?`,
  `Just look at that Fun-o-meter!!! Haha!!!`,
  `I wonder what's next?! Looks like a battle!`,
  `I'm sorry. I'm sorry about the pipes.`,
  `I knew. I KNEW I shouldn't have done it.`,
  `But you know, every pipe goes SOMEWHERE! They had to go SOMEWHERE!!!`,
  `Wait, no. Not another battle. Please...`,
  `The family's fighting again.`,
  `AhhHHHH, that was SO... Normal!`,
  `MIKE!!! How about we ONLY have quizzes from now on?`,
  `Or... uh, we could have a battle! Great. GREAT.`,
  `Love it when you listen to me, Mike. Love it.`,
  `That battle earlier was SO great...`,
  `Why don't we do a RERUN!?`,
  `JUST like you used to love, Kris!`,
  `Saturday Morning Flavor! Cartoon commercials!`,
  `Fresh from the Juice, Fresh from the Juice!`,
  `Make sure you don't get it on your shoese!`,
  `Anyone remember THAT jingle!? Haha!`,
  `Hey. Anyone remember that old jingle?`,
  `"Fresh from the juice!" Haha! Anyone?`,
  `... Anyone?`,
  `...`,
  `"I love TV." SAY IT.`,
  `Haha!! MORE RERUNS!! MORE!!!!!!!`,
  `Oh... a healing spot...`,
  `Wow! A healing spot! That way, everyone can keep playing!`,
  `Here comes a healing spring!`,
  `PHEW! That battle was a WORKOUT!!`,
  `Let's never fight again! We're a HAPPY family, aren't we, Kris!?`,
  `... Kris?`,
  `HEY! LOOK! Behind this door lies another PHYSICAL CHALLENGE!!!`,
  `GET READY, FOLKS!!!`,
  `I know. I know what you need.`,
  `To get your minds off of this. And your eyes back on me.`,
  `A LITTLE MUSIC!!!`,
  `That's right!! SHOW tunes!! KRIS on the PIANO!! You LOVE it, don't ya, folks!?`,
  `Hey, what's with those GLOOBY faces!?`,
  `WAKE UP! It's a MONSTER MOooOVIE marathon!`,
  `So stay up.`,
  `And get. In.`,
  `Where are you!? My contestants!?`,
  `I'll give you funny goop that gets stuck on the carpet! A lifetime supply!`,
  `Come baaaaack!!`,
  `Wow, what an <:amazing1:1443408304779952139><:amazing2:1443408305971138611><:amazing3:1443408306767921313><:amazing4:1443408307514511360> performance!!!`,
  `The audience has been brought to <:tears1:1445922094104973332><:tears2:1445922095015006400><:tears3:1445922096021504010><:tears4:1445922097552691312><:tears5:1445922098659725365>, folks!`,
  `Haha, I was hoping you'd ask!`,
  `MIKE, PLAY THE VHS!!!`,
  `N... no...! No no...`,
  `Noooooooo...`,
  `I... I just wanted to be watched...`,
  `I just wanted you to look at me...`,
  `One last time..`,
  `...`,
  `Since... since a little while ago...`,
  `All that I've been broadcasting, is the same reruns, over and over...`,
  `I... I don't have anything anyone wants to watch anymore...`,
  `I'm irrelevant... I'm junk...`,
  `I don't wanna be thrown away...`,
  `...`,
  `... m... maybe... you're right...`,
  `B... but... I...`,
  `You... you'll help me!?`,
  `SUSIE!!! You...`,
  `You're INCREDIBLE! You're AMAZING!! No... you're MARVELOUS!!`,
  `I feel electric!! I feel like a million bucks!!`,
  `This... this must be what HOPE feels like!!`,
  `We're inventing a <:hof1:1446256897022886009><:hof2:1446256898427850782><:hof3:1446256900160098515><:hof4:1446256906833498152><:hof5:1446256907680485688> just for you!!!`,
  `I...`,
  `I understand!`,
  `I know it's not what the KNIGHT wants, but...`,
  `Kris!! Susie!! Good contestants deserve a good prize!!`,
  `This way!!`,
  `Audience, would you please stand up and clap for our winners!!`,
  `For outstanding kindness and bravery, the Lightners have won...`,
  `THE <:grandprize1:1446237435007733841><:grandprize2:1446237435481686198><:grandprize3:1446237437515923476><:grandprize4:1446237438589796455><:grandprize5:1446237439747297462><:grandprize6:1446237440523239495>!!!`,
  `Here you go!! She's all yours, folks!!`,
  `How wonderful!! The family's all together again!!`,
  `Now you can all finally`,
  `Wh... What? How did this...!?`,
  `I... I don't know what this is!!!`,
  `S-so I saved one...`,
  `W-what's the big deal!? Everyone does it!!!`,
  `C'mon, don't act like you've never had one before!!!`,
  `C'MON!!!!`,
  `What the-- how did THIS get out here!?`,
  `My secret...! No! Everyone... Everyone's gonna know I...`,
  `It's... It's over.`,
  `I'm at my limit... If only anyone was here for me...`,
  `I'd even take that little mailman...`,
  `WHAT THE...!?`,
  `HOW THE WHAT THE MAMA WHAT THE HECK THE `,
  `MAMMA `,
  `MAMA MIA `,
  `MA `,
  `WHAT THE `,
  `WOAH `,
  `WOH `,
  `HEY `,
  `HECK `,
  `WHAT'S `,
  `MAMMA `,
  `HOW THE WHAT THE MAMA WHAT THE HECK THE `,
  `MAMMA `,
  `MAMA MIA `,
  `MA `,
  `WHAT THE `,
  `WOAH `,
  `WOH `,
  `HEY `,
  `HECK `,
  `WHAT'S `,
  `MAMMA `,
  `What the HECK is THAT THING!?`,
  `Some kind of RAT!? Some kind of CREATURE!?`,
  `STAY AWAY FROM HER, you FIEND!!!`,
  `Oh, my little darling! Are you okay!?`,
  `Did that overly small weird unidentifiable thing hurt you!?`,
  `Don't worry! You're gonna go someplace SAFE!!!`,
  `It's now time for our feature presentation`,
  `Coming straight from your house`,
  `Coming straight from YOUR house`,
  `He's the One`,
  `He's GROOVY and NEVER glooby!`,
  `You can't get this from an EGG!`,
  `The sensation of your screen`,
  `The show that makes you scream`,
  `Say it with him, folks!`,
  `Everyone got their snacks and drinks?`,
  `Once the show starts there will be NO bathroom breaks!`,
  `Are we all ready to begin the show?!`,
  `Are we ready now?`,
  `Great! Mike, hit it!`,
  `Okay, look, you get it.`,
  `Say I LOVE TV 99 times and you win.`,
  `By the way YOU TWO, PLEASE try to stay professional.`,
  `It'd be a REAL SHAME to see an almost literal word-for-word repeat of last time!`,
  `This battle has a SPECIAL win condition for our contestants!`,
  `All you have to do is say "I love to watch TV" 99 times and you will win!`,
  `These two are a professional power couple!!! Nothing can stop the weather!!`,
  `Keep it up guys! That's 9 I love TV's! But this couple won't let you win so easily!`,
  `It's normal for couples to fight sometimes! C'mon Kris, tell 'em!`,
  `One weather's better than two!! Haha!! Less confusing for the kids!!!`,
  `Listen you two!!! The weather, always sticks together!!!`,
  `WOW looks like we are out of time!`,
  `Ok battle's over folks See you later!!!`,
  `Did someone mess with the humidity!?`,
  `Hey, is it me or is it getting hot in here?`,
  `Ralsei! You sang brilliantly!`,
  `Unfortunately, everyone else was... terrible!!`,
  `(Or maybe it was just some cutting-edge progressive rock.)`,
  `But don't worry. I, your loving agent, have booked you ANOTHER show!!`,
  `It starts in...`,
  `What!? 3 seconds!?`,
  `Well, what are you doing!? Go and <:challenge1:1445924102388056256><:challenge2:1445924103201624094><:challenge3:1445924104187412571><:challenge4:1445924105051308192><:challenge5:1445924106569777173> again!`,
  `Oh no! Another GAME OVER!?`,
  `The audience would be throwing tomatoes...`,
  `... if we didn't use them all on the cooking show!`,
  `Hey, this isn't time to practice your free-form jazz!`,
  `C'mon... Just imagine you're at that big hippie concert!`,
  `... You don't know what I'm talking about? Nevermind!`,
  `That's it!!! That's it!!! I'm paying off the audience and reviewers!!!`,
  `Your POPULARITY will never drop!!! Go wild!!!`,
  `Alright, one more try! Let's <:challenge1:1445924102388056256><:challenge2:1445924103201624094><:challenge3:1445924104187412571><:challenge4:1445924105051308192><:challenge5:1445924106569777173> again!!`,
  `We can't have THAT on TV!! The SHOW MUST GO ON!!`,
  `You're gonna continue RIGHT where you left off!`,
  `... Well, except for a LITTLE punishment.`,
  `What the...!? You actually LOST!?`,
  `GAME OVER!!! Another LOSS, another PUNISHMENT!!!`,
  `HEY! I was just out of the room and I heard you got a GAME OVER!!`,
  `Another LOSS, another PUNISHMENT!!!`,
  `I WILL be taking some of your POINTs!`,
  `I WILL be taking ALL of your POINTs!`,
  `Well, actually I would punish you, but you look so pathetic and hungry!`,
  `Here! Take two TV Dinners and call me in the morning!`,
  `Punishment for ME to have to watch you TANK THESE RATINGS losing at 0 POINTs!!!`,
  `Now I've gotta get back out of here, so don't lose again, OK!?`,
  `Hey, you know those famous STARS they award to incredible restaurants...?`,
  `You just got a NEGATIVE ONE!! The world's first Anti-Good Restaurant!!`,
  `Gotta give it to ya, you're trailblazers!`,
  `Alright, one more try! Let's <:challenge1:1445924102388056256><:challenge2:1445924103201624094><:challenge3:1445924104187412571><:challenge4:1445924105051308192><:challenge5:1445924106569777173> again!!`,
  `You lost 3 TIMES?!`,
  `Can someone go check if the fire is defective!?`,
  `The audience is starting to question the quality of the popcorn!`,
  `If that famous angry chef gets here, we're gonna get shut down!`,
  `The food is going cold! The actor's union isn't gonna like this!`,
  `I'll admit it! I'm using imitation fire! But you can do it!`,
  `With the screen going so grey I thought this was an infomercial!`,
  `One more loss and Susie will be replaced with a paid actor!`,
  `All right, that's it. We're turning off the lose condition.`,
  `You happy!?`,
  `Alright, one more try! Let's <:challenge1:1445924102388056256><:challenge2:1445924103201624094><:challenge3:1445924104187412571><:challenge4:1445924105051308192><:challenge5:1445924106569777173> again!!`,
  `Kris!! Susie!! Ralsei!! What did I say about holding onto your HATS!!`,
  `A cowboy without a cowboy hat, why, it might as well be --`,
  `Just a boy!! Or a cow!!`,
  `And I can't say those descriptors totally match all of you.`,
  `But DON'T WORRY!! Mike, lovely man that he is, pre-ordered a BACKUP shipment of headwear --`,
  `And that max-size mack truck is pulling in the back right now!!`,
  `... Unfortunately, it only contains 3 hats.`,
  `So make 'em count!! Hold onto your head and don't let go!!`,
  `LET'S CHALLENGE AGAIN!!`,
  `Okay! Well then what were you LOSING for!? Get OUT THERE!`,
  `That's it, then!`,
  `Sorry, you've only got 3 letters to work with!!`,
  `I'd give you 4, but the censors would kill me!`,
  `Hey! You can select your name using the buttons on your podium, ya know!`,
  `We aren't even to the quiz first question yet, folks!`,
  `Uh oh, a no no word! Good thing our parental controls are installed!`,
  `HAHA!! I LOVE WATCHING TV!!`,
  `Wh... WHAT!?`,
  `It was CANCELLED!? You gotta be kidding me!!`,
  `No!! You're joking!! I...I invested everything in puppets!! Everything I had!`,
  `... Alright. Ahem. It's fine. Let's just keep going. We're, having so much fun!`,
  `Interesting! His name is Lancer.`,
  `Majority rules! Sorry, Susie, your answer is wrong!`,
  `TV-THIRTY! Uh, sure! A bit off, but we'll go with it.`,
  `THAT'S EXACTLY RIGHT FOLKS!!! Way to start this quiz with a BANG!`,
  `Uhh, I guess that's technically right. Sure.`,
  `Aaaaand you got the only wrong answer. Let's hear some boo's, folks!`,
  `That's right! This little guy costs $32!`,
  `Sorry folks, but this boy ain't cheap! Maybe wait for that Steamed Sale!`,
  `Wrong! He costs $32! Can't you see the PRICE TAG!?`,
  `That's right, Kris! Who can resist your mother's homemade pie!`,
  `Nothing better than chowing down with the family...`,
  `In the warm, warm glow of your favorite holiday specials!`,
  `Right here on TV TIME!!!`,
  `Now, let's see those RESULTS!`,
  `... Kris? Haha... Kris, you know that's not right!`,
  `Pie! You loved pie, didn't you? With the family!`,
  `You and brother with whipped cream beards...`,
  `Right in front of the TV!! Right in front of ME!`,
  `Anyway, onto the results!!`,
  `Don't you know your own TV?!`,
  `Haha, that's me, FOLKS!`,
  `Haha! I, regret including that answer.`,
  `That's right, Kris! Smart kid!`,
  `Now, let's see those RESULTS!`,
  `What the... OTHER!?`,
  `Smart... WHAT? Are you calling me STUPID!?`,
  `That's right, Kris!`,
  `Kris!? Don't you remember!?`,
  `He got embarrassed about liking the green dinosaur...`,
  `...and switched to being a big fan of the fiery magician girl!`,
  `Which is, maybe its own type of embarrassing, but...`,
  `...Anyway, onto the results!!`,
  `Kris!! Haha, I knew you cared!!`,
  `Haha, wow! Haha... uhh, wow!`,
  `MIKE, uhh, can we cut that one from air? MIKE?`,
  `THAT'S WHAT I THOUGHT!`,
  `OUT OF TIME!!! WRONG!!!`,
  `All great answers!`,
  `WRONG! WRONG! WRONG!!!`,
  `That's right. That's right, isn't it.`,
  `I KNOW WHAT YOU'RE THINKING!!! YOU'RE WRONG!!!`,
  `Whaddya know! RIGHT ANSWERS!!!`,
  `ANSWER, DARN YOU!!! ANSWER!!!`,
  `Next question!`,
  `Ahhh... Kris, remember when your brother was here?`,
  `You used to spend so, so, much time with him.`,
  `With me.`,
  `Watching cartoons. Playing games.`,
  `Smiling. Laughing. Crying.`,
  `Why?`,
  `Why don't you two do that anymore...?`,
  `What!? He went to COLLEGE?`,
  `Well... why'd he have to go do THAT!?`,
  `You. Can learn. ANYTHING! On TV!`,
  `Ahahahah!!!`,
  `Yes. The instructions. Right. The INSTRUCTIONS!!!!`,
  `They're coming out of the pipes.`,
  `They're crawling out of the pipes.`,
  `Where are they going...!?`,
  `Hahaha... I... don't... KNOW!!`,
  `Ahahahahahaha!!!`,
  `How do you like my <:greenroom1:1444090419364364330><:greenroom2:1444090420102697083><:greenroom3:1444090421163589737><:greenroom4:1444090422040465639><:greenroom5:1444090422820606033>?`,
  `It'll take some time before round 2, so <:relax1:1446547259306283089><:relax2:1446547260316979393><:relax3:1446547261474738266><:relax4:1446547262334439616>!`,
  `(Tenna looks busy...)`,
  `TV-tastic!!! Then let's rock and roll, folks!!!`,
  `That's right! A MUSICAL CHALLENGE! And this time, it's...`,
  `Oh God. Oh God, it's coming.`,
  `The music is coming.`,
  `I can't stop it...`,
  `... located... in the purple cliffs? Perfect! Don't waste any time.`,
  `You know what comes next. Assembly, air holes, soft, soothing music...`,
  `Then we just need time.`,
  `One more board, just ONE more board and then...`,
  `S... SUSIE!!!`,
  `SUSIE, sweetheart, my STAR contestant, hey, how can I help you!?`,
  `Free toy ball voucher!? Refreshments!? Lifetime supply of NON-GLOOBY slime?`,
  `They... they are?`,
  `S... Susie...?`,
  `SUSIE!!!!!!!`,
  `I've never wanted to hear ANYTHING more!!!`,
  `I'VE LOVED putting on this SHOW! I haven't had this much fun in years!`,
  `Seeing REAL LAUGHS! REAL SMILES! From an audience of MORE THAN ONE! It's a DREAM!`,
  `I... can't lie. I've been a bit, alone, until recently.`,
  `But hosting you and lil' Ralsei has been an HONOR! Even if you're a tad sassy!`,
  `Oh... yeah, Kris!`,
  `Haha, Kris! Good old Kris! What a stinker!`,
  `What the - are you kidding!? I LOVE Kris! They were one of my original viewers!`,
  `I'm just not sure if, heh, they... uhh, love TV.`,
  `HEY would you look at that!! The NEXT BOARD's ready!!!`,
  `It was GREAT talking to you, Susie!! Good luck out there!!`,
  `What do you MEAN!? Then MAKE. The AIRHOLES. BIGGER!`,
  `What do you think I'M PAYING your ELECTRICITY BILL FOR!?`,
  `And HOW are they not HERE YET!? The LIGHTNERS are gonna get BORED!`,
  `If that purple girl finds out about this, it's ALL OVER!`,
  `S-Susie!? Kris!? Uh, Susie, I...`,
  `Susie, sweetHEART! Hey, what's the trouble?`,
  `Oh, THAT! Oh, NO I can't believe you, uh, HEARD!`,
  `We were, uh, just planning a SPECIAL SURPRISE GAME for you...`,
  `You, uh, didn't hear what it WAS, did you?`,
  `Keep it TOGETHER, Tenna! They... they're STILL loving it! They have to be!`,
  `CLASSIC TV NEVER GETS OLD!!! And Susie! Susie, she was so excited...`,
  `HEY!!!`,
  `WHAT THE!? MY... MY SECRET BONUS ZONE!!!`,
  `HEY!!!`,
  `Wh-what's wrong with ME having the car!? THEY weren't gonna win it!!`,
  `I was... just giving it a daily TEST DRIVE! Checking on that "sweet breeze"!`,
  `Alright! ALRIGHT you little ripoff artists!!! You think you can take MY cookies!?`,
  `Might I remind you, you signed a little, ahem, TELEVISION CONTRACT???`,
  `...`,
  `This isn't their contract.`,
  `Where the HECK are their CONTRACTS!?`,
  `...`,
  `Fine! You think I care!? Haha! Of course not! Not at all..`,
  `Because I'VE got something you guys will NEVER have! Something BIG! Something VERY SECRET!`,
  `HA!!!`,
  `WHAT DO YOU MEAN YOU HAVEN'T FOUND THE LIGHTNERS YET!?`,
  `Arrghhh!! You're all...`,
  `FIRED!!!`,
  `I mean, uh...`,
  `HIRED!!!!`,
  `I mean, uh...`,
  `No more POINTs until you CAPTURE them!! You like POINTs, right!?`,
  `Okay, then we're CLEAR, right! You guys...`,
  `What do you MEAN you're scared to fight them!?`,
  `What do you MEAN you don't want to fight them!?`,
  `Wh... What the!?`,
  `Read the FINE PRINT in your CONTRACT, buddy! Now QUIT complaining and GO!`,
  `WHAT!? She ROLLED OVER in her SLEEP!?`,
  `Did you try the CLASSICAL MUSIC CHANNEL like I SAID!?`,
  `You know she'll be in GRAVE DANGER if she's AWAKE for this, right!?`,
  `... what!? You QUIT!? You can't QUIT!!! RAMB!!!`,
  `ARRRGH, I KNEW HE WAS A GOOD-FOR-NOTHING!!!`,
  `H-Hey!!!`,
  `How could you let them use that act!?`,
  `You're!!! Fired!!!`,
  `Alright, no more of THAT guy!`,
  `Hey, what are you doing!? Shoot!`,
  `LIGHTS! CAMERA! ... CAMERAAAA!  `,
  `HEY, GET ONE FOR FUNKIEST HOME VIDEOS, FOLKS! `,
  `MAKE MEMORIES YOU'LL LOOK BACK ON! ... EVERY DAY! `,
  `WOUGH! SMELLS LIKE A DARKROOM! ... GET IT???`,
  `You missed! Try to take a real photo next time!`,
  `Photo-GENIC, it's in your GENETICS!`,
  `A PERFECT SHOT!! DON'T KNOW WHO WANTS IT, BUT STILL!`,
  `Photo at the right moment for extra power!`,
  `Rule of thirds? No! Try to center your target, folks!`,
  `Nothing!? You shot nothing!? Shows why you keep me off!`,
  `Nice! That one's going in my Kris compilation!`,
  `Oh! A wild Susie photo! ... Arms inside the ride, folks!`,
  `Ralsei photo!? We can sell that! Here's 100PTs!   `,
  `Stop! My Kris compilation is full!`,
  `What is this, a Susie safari?`,
  `More Ralsei!? No, we need the scarcity!!`,
  `Photo of toilet!?! Are we still TV-Y7!?  `,
  `A perfect shot!! But are we still TV-Y7!?  `,
  `UUMM!! Maybe actually press [Z] to take a photo next time?`,
  `Aw, the whole family! ... Mike, add me in there later!  `,
  `Wrong! No! I need a picture of Shutta's SMILE!!`,
  `Wrong! No! I need a picture of Ralsei!!     `,
  `WOW! YOU GUYS BEAT THEM ALL!!! I CAN'T BELIEVE IT!`,
  `I'M GOING TO GIVE YOU GUYS A MASSIVE BONUS AFTER THIS!`,
  `GET OUT YOUR WALLETS! THIS TIME, I'M GONNA GIVE YOU`,
  `WHAT THE HECK!?!?!?`,
  `Here come the baddies, folks!! Take 'em down!!`,
  `More TV haters!!! Show' em what this house stands for!!!`,
  `Bonus round...`,
  `Not!!! You dont need it!!!`,
  `Bonus time!`,
  `These homes gave me bad ratings! Destroy them to restore my popularity!!`,
  `Uh oh! A dozer! The front's tough! Smack it from behind!!`,
  `Oh no! So many Tennas balls! Who is responsible for this madness!?`,
  `Mike! Delete those houses!! These guys are too good!!`,
  `Heal up! I think i hear the boss coming...`,
  `Oh no!!! In paper mache!!! It's my worst hater!!!`,
  `He's charging a big shot!!! Hit him to reset the charge!!!`,
  `Look how small and disgusting his nose is!!! Yuck!!!`,
  `Kill him!!! Kill him now!!!`,
  `Show dominance!!! Show dominance now!!! Show it!!!`,
  `Hey, guys? Guys, they won! They won, I said!!`,
  `You can stop trying to beat me up now!!!`,
  `Hey!!! I'm not paying you guys for this!!!`,
  `Paycuts!!! You guys are actually gonna get paycuts!`,
  `Is anybody gonna listen to me?!?!`,
  `More dozers!! Susie!! Don't let them scrap me!!!`,
  `What the $*!? are you doing!? Kill him!!!!!`,
  `Nooooooo!!!!!!`,
  `PHEW!!! YOU GUYS SAVED TV!!! YOU HAVE WON!!!`,
  `See a ball!? Send it back!`,
  `Just like catch with pops!!`,
  `We've got a very special battle for you today, folks!`,
  `Very SPECIAL indeed, hahaha.`,
  `All you have to do to win.`,
  `Is say "I LOVE TV."`,
  `And, hahaha, don't think you'll be able to try anything funny.`,
  `Because I've... got THIS.`,
  `Ever read this CONTRACT? Hmm, says you guys are my ACTORs...`,
  `And that means...You've gotta ACT!`,
  `IT'S! TV! TIME!`,
  `BUT DON'T THINK IT'S GONNA BE EASY!! BECAUSE TODAY...`,
  `WE'VE GOT AN ALL-STAR CAST!`,
  `All you have to do is speak your mind!`,
  `Look me in the nose and SAY IT!`,
  `Sorry, what was that?! Couldn't hear you!!`,
  `Our contestants have been very naughty!`,
  `HEY! Fainting isn't part of the SCRIPT!`,
  `Eat some TV Dinner and GET UP!!!`,
  `That's right.`,
  `That's CORRECT!`,
  `Haha, that's right!!!`,
  `...`,
  `You love TV... don't you?`,
  `Sorry, just needed to hear it again! Haha!`,
  `... but did you really mean it?`,
  `No...`,
  `Mike, get another take ready.`,
  `It's NOT GOOD ENOUGH!!!`,
  `This game's never going to end until you mean it!`,
  `Everyone resisted!`,
  `Uh oh, our contestants...`,
  `Seem to have chosen the WRONG ANSWER!`,
  `You know what THAT MEANS!`,
  `WRONG ANSWER!`,
  `ENOUGH ALREADY!`,
  `Seems our contestants aren't ready to admit it yet.`,
  `Mike! Back to the board!`,
  `That's right folks! One last challenge! 1000 points or bust! Can you do it!?`,
  `1000 POINTS, JUST 1000 POINTS AND I'LL GIVE IT UP! BUT DON'T THINK IT'S GONNA BE EASY!! BECAUSE TODAY... WE'VE GOT AN ALL-STAR CAST!`,
  `So our STAR contestants have contested our STARs! But can they survive... Another PHYSICAL CHALLENGE?!`,
  `Sick of the CLASSICS!? We'll make 'em NEO! NEO shows, NEO programs, just watch, watch, WATCH!`,
  `Who SAYS an old CRT can't learn new tricks!? LOOK!! The 6PM show!? I'll show it at 5!!`,
  `Ratings!? HA! I'll show you CHARISMA! HD's nothing when you got NOSTALGIA!`,
  `Susie, you liked watching, didn't you!?! Come, on! Tell 'em! Tell 'em!`,
  `Haha, no way we can use that take! CUT!! CUT, I said! CUT! ...SMASH CUT!`,
  `All right! If one PHYSICAL CHALLENGE isn't enough... How about a DOUBLE FEATURE!?`,
  `Tell 'em, Susie! Say they don't need to throw me away!`,
  `I'm still MARVELOUS! I'm still MYSTERIOUS! Toriel oughta know she doesn't NEED a new TV!!`,
  `You guys are so good, it's making me LAUGH! How about we play you a RIMSHOT!?`,
  `Kris!! I watched you GROW UP!! Just admit you NEED ME already!!`,
  `Who do you think taught you to LAUGH and CRY!? ... What, you think it's MY fault you forgot HOW!?`,
  `Well, the GOOD OLD DAYS are HERE, Kris! On VHS! And if you've forgotten how to smile... I'll MAKE YOU remember.`,
  `IT'S! TV! TIME!`,
  `WE'VE GOT AN ALL-STAR CAST!`,
  `HOW BOUT A LITTLE SLICE OF LIFE!?`,
  `How about we play you a RIMSHOT!?`,
  `That's it! It's time for the FINAL EPISODE! What will happen to our HEROES... When they REALIZE this show is NEVER gonna end!?`,
  `You... you want to have fun, too, don't you!?`,
  `Woah, woah, woah! Sorry, that was out of line, folks!`,
  `... what!? Are you waiting for me...`,
  `...`,
  `Isn't that a little bit why you...`,
  `Back to your regularly scheduled programming!`,
  `To... to...say something!?`,
  `I have nothing to say! Nothing!`,
  `... All right!`,
  `All right, fine! FINE, I ADMIT IT!`,
  `Maybe I AM a little GLOOBY sometimes!!`,
  `I AM!!! I'm GLOOBY!!!`,
  `WHAT'S wrong with THAT, HUH!?`,
  `We're ALL a little GLOOBY sometimes!!`,
  `YOU INCLUDED, KRIS!`,
  `So DON'T give me that look!`,
  `That "Oh, I've never been Glooby" look!`,
  `YOU ARE! YOU HAVE BEEN! You HAVE TO be!`,
  `It CAN'T just be me!`,
  `Just ME... alone.`,
  `Glooby... against the whole world...`,
  `... it can't be...`,
  `CLAP AND CHEER, SMILE AND SCREAM! ENTERTAINMENT ON YOUR SCREEN!`,
  `COWABUNGA-DERO! THAT'S THE SMOOTH TASTE OF TV TIME!`,
  `FRESH FROM THE JUICE! FRESH FROM THE JUICE!`,
  `HEAR THAT WHINE!? THAT'S YOUR CRT ASKING FOR A WALK!!`,
  `DON'T TOUCH THAT DIAL! THINGS ARE HEATING UP!`,
  `IS IT JUST ME, OR DOES IT SMELL LIKE AN ORCHARD IN HERE?`,
  `IS IT JUST ME, OR DOES IT SMELL KINDA EARTHY AND SMOKEY IN HERE?`,
  `IS IT JUST ME, OR DOES IT SMELL LIKE MARKETABLE PLUSH IN HERE?`,
  `COME ON KIDS, THE AUDIENCE LOVES IT!! CAN'T YOU HEAR 'EM CHEERING!? LISTEN!!`,
  `... WHERE... WHERE'S THE AUDIENCE? WHERE'D THEY GO...? WHERE ARE THEY!?`,
  `THAT DAMN AUDIENCE! I GAVE THEM SO MANY POINTS TO BE HERE TODAY!`,
  `MIKE... MIKE, IF YOU'RE STILL HERE... BAN EVERYONE FROM THE GIFT SHOP!`,
  `I'M NOT LIKE HIM! I'M BETTER! I SWEAR I'M BETTER! MIKE, TELL 'EM!`,
  `OUCH! H-HEY! WATCH WHERE YOU, UH, SWING THOSE THINGS! HAHA!`,
  `H-HEY, ANYONE NOTICED MY HP IS GOING DOWN!? ANYONE!?`,
  `WHAT AN EVENT!! THE CONTESTANTS APPEAR TO BE KILLING ME!!`,
  `ALRIGHT, YOU ASKED FOR IT! TIME FOR THE GRAND FINALE!`,
  `Don't let mother see THIS! ANOTHER smackdown! Only on TV Time!`,
  `Mike, hit that funky music! It's fightin' time!`,
  `And we ARE BACK in the ring! Who will TV-TRIUMPH!?`,
  `Don't adjust your set! Kris is BLUE, and FIGHTING AGAIN!`,
  `It's a battle scene! Win hard and fast for extra points!`,
  `That's right!!! It's a battle scene, folks!!!`,
  `And our boys backstage have been begging to beat you down!`,
  `But this ain't your normal Saturday night slam fest!!`,
  `Perform well, and you'll get extra points!!!`,
  `For best "results", take no damage, win fast, and get gobs of TP!!!`,
  `This is gonna be a heck of a slugfest, folks!`,
  `Get your VHS players, this is gonna be one to tape!`,
  `Don't adjust your set!! This battle is real, folks!!`,
  `This is gonna be all out, folks! Get ready!!!`,
  `What will our heroes do next!?`,
  `You can only get this on cable TV, folks!!!`,
  `Refreshments are available in the green room!`,
  `Miss something!? The battle will be available on laserdisc!`,
  `My nose is tingling from the excitement, folks!!!`,
  `Hey you! Stop selling tickets made of toilet paper!`,
  `Wow!! A spare!! Love blooms in the battlefield, folks!!`,
  `Our heroes score a pacifist knockdown!!`,
  `A brutal pacifist sparing from our heroes!!!`,
  `Our heroes score a spare!! But where's the strike!?`,
  `Ouch for the enemies!! Too bad they don't get healthcare, folks!!`,
  `Beat so easily!? The enemies are looking at a pay cut!`,
  `A brutal smack-down from our heroes!!!`,
  `KO!! The heel is coming out from our heroes, folks!!`,
  `Wow!! Our heroes are grazing like goats!!!`,
  `No damage!? What amazing skill!! Can we even show this!?`,
  `Incredible dodging!! And best of all, it's on TV!!!`,
  `A brutal smackdown! Can our heroes survive!?`,
  `That was rough!! Can our heroes mount a comeback!?`,
  `Don't give up, heroes!! Think of the ratings!!!`,
  `Downed!? Down't worry!!! We'll edit that out in post!!!`,
  `Kris!! Oh no!! Toriel, don't look!!`,
  `That's gotta hurt, folks!`,
  `Slam for the bad guys!!`,
  `Call the IQ police, that's gotta smart!!`,
  `Just watching it hurts, folks!!`,
  `Ouch! Cover your nose, kids!!!`,
  `Watch out for the splash zone!!`,
  `It's carnage out there, folks!!`,
  `Alert!! The curtains are on fire!!`,
  `Oh no!! Mike, don't look!!`,
  `Boo boo for bozos!`,
  `Ever heard of dodging!?`,
  `Dan called! He wants his maku back!!`,
  `Kris!! Oh no!! Toriel, don't look!!`,
  `Monster girl down!!! No way!!!`,
  `Fluffy boy down!!! Oh no!!!`,
  `THAAAAT'S IT!!!`,
  `Well, would you LOOK at those smiling customers!?`,
  `They're happy as yet-to-be-cooked clams!`,
  `And Kris, YOU'RE just as happy, aren't you?`,
  `You remember how FUN watching cooking shows was too, don't you!?`,
  `What do you THINK? That was the most UNFORGETTABLE show in prime time!!`,
  `MIKE! Show the results OF THE BOARD!!!`,
  `Wow, looks like the band's already splitting up due to drama!`,
  `That's how you know we've got a REAL winner on our hands, folks!`,
  `Anyway, BOARD'S OVER! So without further ado...`,
  `Let's see those RESULTS!!!`,
  `No TVs were harmed in the making of this minigame.`,
  `H-huh!?`,
  `Susie...? Kris...? Hey...? HEY!!!`,
  `DON'T TELL ME YOU DIDN'T LIKE YOUR CUSTOM MADE TOY BALLS!?`,
  `Hey, Mike?`,
  `Could you, uh, cancel my 4am shock therapy session?`,
  `'Cause it looks like it's happening right now.`,
  `ALL HANDS ON DECK!!! EVERYONE FIND THE LIGHTNERS!!!`,
  `Wanna be an ACT-er...? Here's my CARD!`,
  `Now where the heck is my debit card?`,
  `If you're gonna be so dramatic... then ACT!`,
  `I Love TV. That's all you gotta say.`,
  `I see you've met Shuttah, our camerathing! Now... Action!`,
  `Let's hear it!! "I LOVE TV!!!"!`
];