const handler = require('../../src/features/conversation/handler.js'); 
const examples = [
  // empty
  ['empty', ''],

  // fallback
  ['fallback', 'sdkfjdshfsd'],
  ['fallback', 'lalalalalalala'],

  // tier1_blockers
  ['offLimits', 'wireplay'],

  // tier2_questionsToTenna
  ['askTennaAwake', 'are you up'],
  ['askTennaAwake', 'you awake?'],
  ['askTennaAwake', 'are u there'],
  ['askTennaAwake', 'are you here???'],
  ['askTennaGoodBoy', 'who is a good boy'],
  ['askTennaGoodBoy', "who's a good boy???"],
  ['askTennaGoodBoy', 'good boy!!'],
  ['askTennaGoodBoy', 'who is a good tv'],
  ['askTennaLikeGender', 'are you into dudes?'],
  ['askTennaLikeGender', 'do you like enbies??'],
  ['askTennaLikeGender', 'you into women?'],
  ['askTennaLikeGender', 'you like boys?'],
  ['askTennaFlirt', 'do you have a boyfriend?'],
  ['askTennaFlirt', 'got a gf?'],
  ['askTennaFlirt', 'do you wanna go out?'],
  ['askTennaFlirt', 'wanna date me??'],
  ['askTennaFlirt', 'touches your nose'],
  ['askTennaFlirt', 'gropes your dials'],
  ['askTennaFlirt', 'kiss me!!!'],
  ['askTennaFlirt', 'can you kiss me'],
  ['askTennaFlirt', 'licking your screen'],
  ['askTennaFlirt', 'are you interested in anyone?'],
  ['askTennaFlirt', 'are you taken'],
  ['askTennaFlirt', 'will you marry me?'],
  ['askTennaFlirt', 'do you have a crush on someone?'],
  ['askTennaFlirt', 'do you like someone?'],
  ['askTennaFlirt', 'are you seeing anyone?'],
  ['askTennaFlirt', 'caress your buttons'],
  ['askTennaFlirt', 'wanna be my boyfriend?'],

  // tier3_commands

  // tier4_conversational

  // tier5_characters

  // tier6_otherMentions

  // tier7_compliments
  ['loveFans', 'can you say you love your fans'],
  ['loveFans', 'will you say you love us?'],
  ['loveFans', 'would you say you love your fans?'],
  ['loveFans', 'can you say you love me'],
  ['loveFans', 'can you say that you love me'],
  ['loveFans', 'do you love fans'],
  ['hugFans', 'tenna can you hug me'],
  ['hugFans', 'tenna can I get a hug?'],
  ['hugFans', 'could you hug me?'],
  ['hugFans', 'could I have a hug?'],
  ['hugFans', 'could you give me a hug?'],
  ['hugFans', 'could I get a sloppy kiss?'],
  ['hugFans', 'will you pat me'],

  // tier8_insults

  // tier9_userState

  // tier10_selfQuestions
  ['selfQuestionWhy', 'why are you like this'],
  ['selfQuestionWhy', 'why must you be like this'],
  ['selfQuestionWhy', 'why cant you understand me???'],
  ['selfQuestionWhy', 'why would you hurt me'],
  ['selfQuestionWhy', "why don't you hit the bricks"],
  ['selfQuestionWhy', 'whyyyyy tenna'],
  ['selfQuestionWhy', 'tenna why, just why'],
  ['selfQuestionCanYou', 'could you please stop'],
  ['selfQuestionCanYou', 'can you do a trick?'],
  ['selfQuestionCanYou', 'are you able to hang out later?'],
  ['selfQuestionCanYou', 'are you gonna chill out'],
  ['selfQuestionWho', 'who are you??'],
  ['selfQuestionWho', 'who even are you'],
  ['selfQuestionWho', 'who is tenna??'],
  ['selfQuestionWho', "who's this guy?"],
  ['selfQuestionWho', "who're you"],
  ['selfQuestionWho', 'who the fuck is this guy'],
  ['selfQuestionHow', 'are you okay??'],
  ['selfQuestionHow', 'how you doin'],
  ['selfQuestionHow', 'r u ok'],
  ['selfQuestionHow', 'how is it going'],
  ['selfQuestionHow', 'how it going'],
  ['selfQuestionHow', "how's it hangin"],
  ['selfQuestionHow', 'how art thou'],
  ['selfQuestionHow', 'is your day going okay?'],
  ['selfQuestionHow', 'has your day been good?'],
  ['selfQuestionHow', 'how was your day?'],
  ['selfQuestionHow', 'how r ya'],
  ['selfQuestionHow', 'are u alright'],
  ['selfQuestionHow', 'are you doing alright'],
  ['selfQuestionWhatsUp', 'what is going on'],
  ['selfQuestionWhatsUp', "what's happening"],
  ['selfQuestionWhatsUp', 'what is happenin'],
  ['selfQuestionWhatsUp', 'what is going down'],
  ['selfQuestionWhatsUp', 'wassup'],
  ['selfQuestionWhatsUp', 'waaaasssuuuup'],
  ['selfQuestionWhatsUp', 'wazzuup'],
  ['selfQuestionWhatsUp', 'watcha doin'],
  ['selfQuestionWhatsUp', "what're you up to"],
  ['selfQuestionWhatsUp', 'sup'],
  ['selfQuestionWhat', 'what even are you'],
  ['selfQuestionWhat', 'what the fuck is tenna'],
  ['selfQuestionWhat', 'what is a tenna'],
  ['selfQuestionWhat', 'what do you even do'],
  ['selfQuestionWhat', 'what are you'],
  ['selfQuestionWhat', 'what the hell are you'],
  ['selfQuestionOpinion', 'how do you respond to the allegations'],
  ['selfQuestionOpinion', 'what do you think about'],
  ['selfQuestionOpinion', 'how do you feel about this'],
  ['selfQuestionOpinion', 'what is your take on'],
  ['selfQuestionOpinion', "what's your opinion"],
  ['selfQuestionOpinion', 'what would you say about'],
  ['selfQuestionOpinion', 'how do you react to'],
  ['selfQuestionWhere', 'where are you'],
  ['selfQuestionWhere', 'where r you'],
  ['selfQuestionWhere', 'where are you at'],
  ['selfQuestionWhere', 'where do you live'],
  ['selfQuestionWhere', 'where you at'],
  ['selfQuestionWhere', 'where are you staying'],
  ['selfQuestionWhere', 'where is tenna'],
  ['selfQuestionWhere', 'where do you come from'],
  
  // tier11_tvQuestions
  ['tvQuestionWhen', 'when is the next show?'],
  ['tvQuestionWhen', 'what time is the next episode'],
  ['tvQuestionWhen', "when's the broadcast???"],
  ['tvQuestionWhen', 'when is tv time'],
  ['tvQuestionWhen', 'WHEN TV TIME, TENNA'],
  ['tvQuestionWhen', 'what time are you on air'],
  ['tvQuestionWhen', 'when do you go on air?'],
  ['tvQuestionRating', 'how are the ratings?'],
  ['tvQuestionRating', 'are ratings low?'],
  ['tvQuestionRating', 'are you popular?'],
  ['tvQuestionRating', 'how many fans do you have??'],
  ['tvQuestionRating', 'how well is the show going?'],
  ['tvQuestionRating', 'do you get a lot of viewers?'],
  ['tvQuestionRating', 'how is tv time'],
  ['tvQuestionWhat', 'What show do you host again?'],
  ['tvQuestionWhat', 'what is the name of your show'],
  ['tvQuestionWhat', 'which channel is your show on?'],
  ['tvQuestionWhat', 'what channel is tv time on'],
  ['tvQuestionWhat', 'what is your channel??'],
  ['tvQuestionWhat', 'which program should I watch?'],
  ['tvQuestionHow', 'how do I watch tv time??'],
  ['tvQuestionHow', 'how can I tune in'],
  ['tvQuestionHow', 'how can I find you'],
  ['tvQuestionHow', 'how watch'],
  ['tvQuestionHow', 'how do I see your show tenna??'],

  // tier12_greetings
  ['goodMorning', 'good morning!!'],
  ['goodMorning', 'morning tenna!!'],
  ['goodMorning', "g'morning tenna"],
  ['goodMorning', 'morning'],
  ['goodMorning', "mornin'"],
  ['goodMorning', 'morning'],
  ['goodMorning', 'gm'],
  ['goodMorning', 'rise and shine tenna!'],
  ['goodnight', 'nighty night'],
  ['goodnight', 'good night'],
  ['goodnight', "g'night tenna!"],
  ['goodnight', 'nighttttt'],
  ['goodnight', 'niiiiight'],
  ['goodnight', 'sleep tight tenna!'],
  ['goodnight', 'have a good night tenna!'],
  ['goodnight', 'night night!'],
  ['goodnight', 'nini!'],
  ['goodbye', 'byeee tennaaaa'],
  ['goodbye', 'byyyeee'],
  ['goodbye', 'good bye'],
  ['goodbye', 'goodbye'],
  ['goodbye', 'seeyaa'],
  ['goodbye', 'bye byeee'],
  ['greeting', 'Hi Tenna!!'],
  ['greeting', 'Hello'],
  ['greeting', 'Yoooo Tenna!!!'],
  ['greeting', 'yo'],
  ['greeting', 'heyyyyyaa'],
  ['greeting', 'Heyyyy'],
  ['greeting', 'hiiii mr tenna'],
  ['greeting', 'hewwo'],
]

describe('Dialogue Handler Tests', () => {
  for (const content of examples) {
    it(`should correctly detect "${content[1]}" as ${content[0]}`, () => {
      expect(handler.detectIntent(content[1])).toBe(content[0]);
    });
  }
});