const handler = require('../../src/features/conversation/handler.js'); 
const examples = [
  // empty
  ['empty', ''],

  // fallback
  ['fallback', 'sdkfjdshfsd'],
  ['fallback', 'lalalalalalala'],

  // tier1_blockers
  ['offLimits', 'wireplay'],
  ['offLimits', 'slaps ur boner'],

  // tier2_questionsToTenna
  ['askTennaAwake', 'are you up'],
  ['askTennaAwake', 'you awake?'],
  ['askTennaAwake', 'are u there'],
  ['askTennaAwake', 'are you here???'],
  ['askTennaGoodBoy', 'who is a good boy'],
  ['askTennaGoodBoy', "who's a good boy???"],
  ['askTennaGoodBoy', 'good boy!!'],
  ['askTennaGoodBoy', 'who is a good tv'],
  ['askTennaLikeGender', 'are you into dudes?'],
  ['askTennaLikeGender', 'do you like enbies??'],
  ['askTennaLikeGender', 'you into women?'],
  ['askTennaLikeGender', 'you like boys?'],
  ['askTennaFlirt', 'do you have a boyfriend?'],
  ['askTennaFlirt', 'got a gf?'],
  ['askTennaFlirt', 'do you wanna go out?'],
  ['askTennaFlirt', 'wanna date me??'],
  ['askTennaFlirt', 'touches your nose'],
  ['askTennaFlirt', 'gropes your dials'],
  ['askTennaFlirt', 'kiss me!!!'],
  ['askTennaFlirt', 'can you kiss me'],
  ['askTennaFlirt', 'licking your screen'],
  ['askTennaFlirt', 'are you interested in anyone?'],
  ['askTennaFlirt', 'are you taken'],
  ['askTennaFlirt', 'will you marry me?'],
  ['askTennaFlirt', 'do you have a crush on someone?'],
  ['askTennaFlirt', 'do you like someone?'],
  ['askTennaFlirt', 'are you seeing anyone?'],
  ['askTennaFlirt', 'caress your buttons'],
  ['askTennaFlirt', 'wanna be my boyfriend?'],
  ['askTennaLove', 'do you love me?'],
  ['askTennaLove', 'do you love your fans'],
  ['askTennaLove', "don't you love your show??"],
  ['askTennaLove', 'you love tv'],
  ['askTennaLove', 'you love your fans, dont u'],
  ['askTennaLove', 'do u rly love television'],
  ['askTennaLove', 'do you love your job???'],
  ['askTennaAge', 'what year were u born??'],
  ['askTennaAge', 'what is your age'],
  ['askTennaAge', "what's your age"],
  ['askTennaAge', 'how old ARE you'],
  ['askTennaAge', 'how old r u'],
  ['askTennaAge', 'are you old'],
  ['askTennaAge', 'what year were u born'],
  ['askTennaAge', 'how old is tenna?'],
  ['askTennaAge', 'is tenna old?'],
  ['askTennaRemember', 'do you remember the time when'],
  ['askTennaRemember', 'you remember, right?'],
  ['askTennaRemember', 'dont u remember me'],
  ['askTennaRemember', 'can you remember that?'],
  ['askTennaRemember', 'did you forget about me'],
  ['askTennaRemember', 'remember when that happened?'],
  ['askTennaKnow', 'what do you know about this?'],
  ['askTennaKnow', 'have you learned about discord?'],
  ['askTennaKnow', 'what do you hear about me'],
  ['askTennaKnow', 'have you heard about'],
  ['askTennaKnow', 'ever hear of'],
  ['askTennaKnow', 'have you heard who'],
  ['askTennaKnow', 'did you hear about anything'],
  ['askTennaKnow', 'did u hear anything'],
  ['askTennaKnow', 'what do you know of deltarune'],

  // tier3_commands
  ['quizCommand', 'give me a quiz'],
  ['quizCommand', 'can I have a quiz'],
  ['quizCommand', 'do a quiz'],
  ['quizCommand', 'give quiz'],
  ['quizCommand', 'quiz them'],
  ['quizCommand', 'quiz me!!!'],
  ['quizCommand', 'want a quiz'],
  ['quizCommand', 'quiz her NOW'],
  ['quizCommand', 'tenna can I do a quiz'],
  ['quizCommand', 'can I try quiz'],
  ['balanceCommand', 'how much do they have'],
  ['balanceCommand', 'where are my points'],
  ['balanceCommand', 'how many points do I have??'],
  ['balanceCommand', 'how many do I have'],
  ['balanceCommand', 'what is my balance'],
  ['balanceCommand', 'what is my points balance'],
  ['balanceCommand', 'show my points'],
  ['balanceCommand', 'how do I check my points?'],
  ['introduceCommand', 'my name is'],
  ['introduceCommand', 'my birthday is'],
  ['introduceCommand', 'my pronouns are'],
  ['introduceCommand', 'my nickname is'],
  ['introduceCommand', 'I want to introduce myself'],
  ['introduceCommand', 'want to know my name?'],
  ['introduceCommand', 'wanna learn my birthday?'],
  ['introduceCommand', 'wanna hear my nickname?'],
  ['scheduleCommand', 'schedule an event please!'],
  ['scheduleCommand', 'tenna can you make a watch party for us'],
  ['scheduleCommand', 'tenna can you make a writing sprint for us'],
  ['scheduleCommand', 'start the event'],
  ['scheduleCommand', 'plan a party for meeee'],
  ['scheduleCommand', 'set my party!!'],
  ['scheduleCommand', 'create an event tenna!!'],
  ['gachaCommand', 'how do I do the gacha'],
  ['gachaCommand', 'i wanna roll for prizes'],
  ['gachaCommand', 'how do I get prizes????'],
  ['gachaCommand', 'where is the prize ball machine'],
  ['sellbackCommand', 'can I sell this back to you'],
  ['sellbackCommand', 'how do I sellback?'],
  ['inventoryCommand', 'what are my items?'],
  ['inventoryCommand', 'where is my inventory?'],
  ['inventoryCommand', 'where are my prizes?'],
  ['inventoryCommand', 'where can I see my prize??'],
  ['quoteCommand', 'can I get a nice quote please'],
  ['quoteCommand', 'give us a quote'],
  ['quoteCommand', 'can you do one of your famous lines?'],
  ['giveCommand', 'how do I give stuff?'],
  ['giveCommand', 'can I give Jay my prize?'],
  ['giveCommand', 'how do I give my item away?'],
  ['giveCommand', 'I want to send a gift'],
  ['giveCommand', 'I want give something'],
  ['freePointsCommand', 'can you give me points'],
  ['freePointsCommand', 'can I get more points'],
  ['freePointsCommand', 'give me free points'],
  ['freePointsCommand', 'i want points'],
  ['freePointsCommand', 'can you give me 15 more points for the gacha'],
  ['freePointsCommand', 'add 100 points please'],
  ['freePointsCommand', 'can i have some points pls?'],
  ['takePointsCommand', 'TENNA TAKE JAYS POINTS AWAY'],
  ['takePointsCommand', 'can you steal 15 points from skittle'],
  ['takePointsCommand', 'delete their points please'],
  ['takePointsCommand', "can i have Gab's points?"],

  // tier4_conversational
  ['tennaQuoteTVTime', 'what time is it??'],
  ['tennaQuoteTVTime', 'its TV TIME!!!'],
  ['tennaQuoteTVTime', "It's T! V! TIME!"],
  ['tennaQuoteTVTime', 'say it with him folks!!'],
  ['tennaQuoteJuice', 'turn up the juice! turn up the juice!!!'],
  ['tennaQuoteJuice', 'fresh from the juice!!!'],
  ['tennaQuoteKillThisGuy', 'how do I kill this guy?'],
  ['tennaQuoteKillThisGuy', 'kill tenna NOW'],
  ['tennaQuoteKillThisGuy', 'how do we kill this guy'],
  ['tennaQuoteDial', 'dont touch that dial!'],
  ['tennaQuoteFamilyFight', 'the family is fighting again'],
  ['tennaQuoteFamilyFight', "family's fighting again"],
  ['canYouEncourage', 'Can I have some words of encouragement'],
  ['canYouEncourage', 'i need some words of encouragement to do some work. pls be nice to me or i will cry'],
  ['canYouEncourage', 'I have to go back to work today. Can I get some encouragement? (and a cupa coffee)'],
  ['canYouEncourage', 'I need some motivation'],
  ['canYouEncourage', 'can I get words of wisdom'],
  ['canYouEncourage', 'could you give me some well wishes?'],
  ['canYouEncourage', 'could you give me encouragement?'],
  ['canYouEncourage', 'Can I get some encouragment'],
  ['canYouEncourage', 'can i have some hope'],
  ['sayThankYou', "You're doing a great job, Tenna!"],
  ['sayThankYou', 'Tenna is very good at his job'],
  ['sayThankYou', 'Tenna, you get an A+ from me'],
  ['sayThankYou', 'great work!'],
  ['sayThankYou', 'proud of you pookie'],
  ['sayThankYou', "You've done a great job!"],
  ['sayThankYou', 'nice ass'],
  ['sayThankYou', "you've got a great ass!"],
  ['sayThankYou', 'You are so charismatic'],
  ['sayThankYou', "You're a great host!"],
  ['sayThankYou', 'You got a really good work ethic!'],
  ['saySorry', 'knock it off Tenna'],
  ['saySorry', 'BE NICE'],
  ['saySorry', 'say your sorry NOW'],
  ['saySorry', 'tenna quit it'],
  ['saySorry', 'stop that'],
  ['saySorry', 'can you say something nice'],
  ['saySorry', 'say psyche right now'],
  ['saySorry', "I'm so mad at you rn"],
  ['saySorry', "they're so mad at you"],
  ['saySorry', "say you're sorry"],
  ['saySorry', 'apologize to them!!'],
  ['saySorry', 'say something nicer to me'],
  ['saySorry', 'say you didnt mean it.....'],
  ['saySorry', "don't be mean"],
  ['saySorry', 'AYYYOOOO'],
  ['saySorry', 'ayo??'],
  ['imSorry', 'IM SO SOWWY TENNAAAA'],
  ['imSorry', "I'm so fucking sorry tenna"],
  ['imSorry', 'i am sorry'],
  ['imSorry', 'please forgive me'],
  ['imSorry', 'FORGIVE HER PLEASEEE'],
  ['imSorry', 'forgiiiiive meeeeeee'],
  ['imSorry', 'im sowwwwyyyyy'],
  ['imSorry', 'sorry tenna...'],
  ['dontWorry', "don't worry about it!"],
  ['dontWorry', "Don’t worry about it :3"],
  ['dontWorry', 'no worries kitten'],
  ['dontWorry', 'eh forget about it'],
  ['dontWorry', 'ignore them, tenna'],
  ['dontWorry', 'forget that'],
  ['dontWorry', 'its all good'],
  ['dontWorry', "it's all right!"],
  ['dontWorry', 'its all okay'],
  ['dontWorry', 'do not worry my silly little tv'],
  ['dontWorry', 'ignore me okay'],
  ['youllSee', 'oh youll find out'],
  ['youllSee', "you'll see soon...."],
  ['youllSee', 'you will'],
  ['youllSee', 'you will seeeee'],
  ['youllSee', 'youuuu willlll'],
  ['getYou', 'IM GONNA GET YOU!!!!'],
  ['getYou', 'me when i fucking get you'],
  ['getYou', "I'm going to fucking get you"],
  ['getYou', 'dont make me get you'],
  ['getYou', "I'm gonna get your ass"],
  ['getYou', 'when I get my hands on you!!!'],
  ['getYou', 'ONCE I GET A HOLD OF YOU'],
  ['getYou', "I'm gonna beat you up"],
  ['thankYou', 'thank you tennaaaa'],
  ['thankYou', 'Thanks babe'],
  ['thankYou', 'big thank'],
  ['thankYou', 'thanks tenna!!!!'],
  ['thankYou', 'Great! Thanks for your patience during testing, Tenna!'],
  ['thankYou', 'thaaaaaanks tenna!!!!'],
  ['thankYou', 'ty'],
  ['thankYou', 'I said thank you, idiot'],
  ['bark', 'your a puppy'],
  ['bark', "You're a doggo"],
  ['bark', 'youre a silly pup'],
  ['bark', 'walkies?'],
  ['bark', 'i demand that you bark for us'],
  ['bark', 'command you to bark'],
  ['bark', 'BARK FOR ME'],
  ['bark', 'bark NOW'],
  ['bark', 'bark RIGHT NOW!!!'],
  ['dontWannaGetUp', 'Help me get out of bed please'],
  ['dontWannaGetUp', 'can you get me out of bed'],
  ['dontWannaGetUp', 'tell me to wake up'],
  ['dontWannaGetUp', 'make me get up'],
  ['dontWannaGetUp', 'tell me to get out of bed'],
  ['dontWannaGetUp', 'Should I get out of bed?'],
  ['dontWannaGetUp', 'I just want to stay in bed all day'],
  ['dontWannaGetUp', "I don't wanna get up"],
  ['dontWannaGetUp', "can you wake me up"],
  ['dontWannaGetUp', "can you get me up"],
  ['dontWannaGetUp', "Is it time for me to get up?"],
  ['dontWannaGetUp', "is it time to get out of bed?"],
  ['sleepIn', 'can I sleep in?'],
  ['sleepIn', 'can I stay in bed all day?'],
  ['helpGoToSleep', 'I just want to sleep, can you please read me a bedtime story'],
  ['helpGoToSleep', 'Can you carry me to bed at least'],
  ['helpGoToSleep', 'tuck me into bed please'],
  ['helpGoToSleep', 'take me to bed!!! wink'],
  ['helpGoToSleep', 'Should I go to sleep'],
  ['helpGoToSleep', 'i need to go to sleep'],
  ['helpGoToSleep', 'Should I go sleep then'],
  ['goToBed', 'go to bed Tenna!!!'],
  ['goToBed', 'you should go to sleep yourself'],
  ['goToBed', 'GO TO SLEEP'],
  ['goToBed', 'get some rest'],
  ['goToBed', 'are you sleepy?'],
  ['dontWannaGoToWork', 'should i be naughty and leave work 15 mins early'],
  ['dontWannaGoToWork', 'i dont wanna go my job'],
  ['dontWannaGoToWork', 'i dont want to go to my job'],
  ['dontWannaGoToWork', 'i hate work please for the love of god help me tenna'],
  ['dontWannaGoToWork', "I don't wanna go into work today!!"],
  ['dontWannaGoToWork', 'can I stop working please'],
  ['dontWannaGoToWork', 'do I have to go to work today??'],
  ['dontWannaGoToWork', 'can i quit my job please'],
  ['tellMeLockIn', 'Tenna, can you tell me to lock the fuck in?'],
  ['tellMeLockIn', 'tell me to lock in'],
  ['tellMeLockIn', 'can you help me focus'],
  ['tellMeLockIn', 'tell me to focus please'],
  ['tellMeLockIn', 'say I gotta lock in'],
  ['tellMeLockIn', 'Do I need to lock in?'],
  ['tellMeLockIn', 'I need to get back to work'],
  ['tellMeLockIn', 'Tell me to go back to work'],
  ['tellMeLockIn', 'can you kick my ass i need to start drawing'],
  ['tellMeLockIn', "I can't concentrate"],
  ['canYouBonkMe', 'can you bonk me on the head'],
  ['canYouBonkMe', 'can you kick my ass'],
  ['canYouBonkMe', 'beat me up please'],
  ['canYouBonkMe', 'punch me in the face'],
  ['canYouBonkMe', 'dropkick me'],
  ['canYouBonkMe', 'can you remove my brain'],
  ['canYouBonkMe', 'can you take my brain out'],
  ['canYouBonkMe', 'could you knock me out'],
  ['canYouBonkMe', 'i want you to snap me in half please'],
  ['canYouBonkMe', 'Can you hit me with hammers?'],
  ['canYouBlowMeUp', 'my main goal is to blow up'],
  ['canYouBlowMeUp', 'can you blow me up'],
  ['canYouBlowMeUp', 'i need you to explode me'],
  ['canYouBlowMeUp', 'can you blow up my brain'],
  ['canYouBlowMeUp', 'i need to explode'],
  ['canYouBlowMeUp', "I'm gonna blow up"],
  ['canYouBlowMeUp', 'im blowing up'],
  ['canYouBlowMeUp', 'Can you make me explode'],
  ['canYouBlowMeUp', 'blow me up'],
  ['stopBeingHorny', 'Okay you need to chill with being so horny'],
  ['stopBeingHorny', 'why are you always horny'],
  ['stopBeingHorny', 'why are you so horny'],
  ['stopBeingHorny', 'Are you being horny in gen again'],
  ['stopBeingHorny', 'YOU GOT THE HORNY PASS'],
  ['stopBeingHorny', 'STOP BEING HORNY'],
  ['stopBeingHorny', 'ur being a pervert'],
  ['stopBeingHorny', "you're a pervert!!"],
  ['stopBeingHorny', "you're a perv!!"],
  ['stopBeingHorny', "you're horny!!"],
  ['stopBeingHorny', 'u horny'],
  ['stopBeingHorny', 'you perv'],
  ['stopBeingHorny', "You're a lil freak"],
  ['stopBeingHorny', 'your exhibitionism is showing'],

  // tier5_characters
  ['spamtonMention', 'do you miss your ex partner?'],
  ['spamtonMention', 'do you miss your ex?'],
  ['spamtonMention', 'where is the email guy?'],
  ['spamtonMention', 'spammy'],
  ['mikeMention', 'mike!!!'],
  ['pipisMention', 'pipis????'],
  ['susieMention', 'do you like snoozie?'],
  ['ralseiMention', 'who is ralsei'],
  ['torielMention', 'do you like Tori?'],
  ['familyMention', 'where is dess'],
  ['knightMention', 'what can you say about the knight'],
  ['queenMention', 'queenie beenie'],
  ['lancerMention', 'lancer'],
  ['kingMention', 'why did you call him kingy doodle'],
  ['mettatonMention', 'would you go out with mettaton'],
  ['laninoElninaMention', 'lanino!'],
  ['laninoElninaMention', 'elnina!'],
  ['laninoElninaMention', 'the weather duo!'],
  ['workersMention', 'do you pay battat enough'],
  ['workersMention', 'WHERE IS MY LITTLE PLUEY'],
  ['whoMention', 'rouxls'],
  ['whoMention', 'Do you like Toby Fox'],

  // tier6_otherMentions
  ['emailMention', 'what is an e-mail?'],
  ['mikuMention', 'Would you duet with Miku??'],
  ['mikuMention', 'do you like Vocaloid?'],
  ['discordMention', 'having fun in this server?'],
  ['discordMention', 'how did you learn discord'],
  ['discordMention', 'who taught you the internet'],
  ['discordMention', 'how did you get online?'],
  ['beingBotMention', 'wait are you ai'],
  ['beingBotMention', 'are you a chat bot'],
  ['beingBotMention', "aren't you a chat bot"],
  ['beingBotMention', 'u r bot'],
  ['beingBotMention', 'your a computer program'],
  ['beingBotMention', 'are you real'],

  // tier7_compliments
  ['loveFans', 'can you say you love your fans'],
  ['loveFans', 'will you say you love us?'],
  ['loveFans', 'would you say you love your fans?'],
  ['loveFans', 'can you say you love me'],
  ['loveFans', 'can you say that you love me'],
  ['loveFans', 'do you love fans'],
  ['hugFans', 'tenna can you hug me'],
  ['hugFans', 'tenna can I get a hug?'],
  ['hugFans', 'could you hug me?'],
  ['hugFans', 'could I have a hug?'],
  ['hugFans', 'could you give me a hug?'],
  ['hugFans', 'could I get a sloppy kiss?'],
  ['hugFans', 'will you pat me'],
  ['hugFans', 'HUG THEM NOW'],
  ['hugFans', 'JAY NEEDS A HUG PLEASE'],
  ['hugFans', 'could I get some love?'],
  ['hugFans', 'kiss pls'],
  ['iLoveTV', 'I love you'],
  ['iLoveTV', 'we LOVE TV!!!'],
  ['iLoveTV', 'i fucking love tenna'],
  ['iLoveTV', 'ilovetv'],
  ['iLoveTV', 'I LOVE WATCHING TV'],
  ['iLoveTV', 'I LOVE TENNA'],
  ['compliment', 'you are SO CUTIEFUL'],
  ['compliment', 'your hot'],
  ['compliment', "you're so handsome!"],
  ['compliment', 'ur hot'],
  ['compliment', 'you look so cute'],
  ['compliment', 'you are a funny man'],
  ['compliment', 'your so nice!!!'],
  ['compliment', "you're very handsome"],
  ['compliment', "you're really sweet!"],
  ['compliment', "you're delightfully babygirl"],
  ['compliment', "You're a baddie"],
  ['compliment', "You're too cute"],
  ['physicalAffection', 'kisses you'],
  ['physicalAffection', 'hugs you'],
  ['physicalAffection', 'im smooching u'],
  ['physicalAffection', 'pats your nose'],
  ['physicalAffection', 'cuddle tenna'],
  ['physicalAffection', 'slaps your ass'],
  ['physicalAffection', 'slapping ur booty'],
  ['physicalAffection', 'MWAH'],
  ['physicalAffection', 'MWAAAAAH'],
  ['physicalAffection', 'MWA'],
  ['physicalAffection', 'SMOOCH'],

  // tier8_insults
  ['insultBoo', 'BOO YOU SUCK'],
  ['insultBoo', 'BOOO'],
  ['insultBoo', 'booooo stinky'],
  ['insultBoo', 'BOO UR BORING'],
  ['insultBoo', 'GET OFF THE STAGE'],
  ['insultOld', 'you are SO OLD'],
  ['insultOld', 'you are an old tv!!'],
  ['insultOld', "you're ancient!!!"],
  ['insultOld', "OLD MAN"],
  ['insultOld', "god ur old"],
  ['insultOld', "u r a boomer"],
  ['insultOld', "okay boomer"],
  ['insultOld', "you an old bitch"],
  ['insultShutUp', 'dude, shut up'],
  ['insultShutUp', 'shut the FUCK UP!!!'],
  ['insultShutUp', 'leave me alone'],
  ['insultShutUp', 'who asked'],
  ['insultShutUp', 'stop bitching'],
  ['insultShutUp', 'what are u yapping about'],
  ['insultShutUp', 'please be quiet'],
  ['insult', 'you are an idiot'],
  ['insult', 'you suck'],
  ['insult', 'you a BITCH'],
  ['insult', 'ur a meanie!!!'],
  ['insult', "god you're stupid"],
  ['insult', "you're lame and annoying"],
  ['insult', "u r so rude"],
  ['insult', "kill urself mr tenna"],
  ['insult', "KILLS YOU WITH MY MIND!!!"],
  ['insult', "TRASH HEAP!!!"],
  ['insult', ":tennafuckyou:"],
  ['physicalViolence', 'bites you'],
  ['physicalViolence', 'kicks your shins'],
  ['physicalViolence', 'punches your screen'],
  ['physicalViolence', 'BEATING YOU UP'],
  ['physicalViolence', 'throwing you down the stairs'],
  ['physicalViolence', 'ripping off your nose'],
  ['physicalViolence', 'shocking tenna'],
  ['physicalViolence', 'steals your debit card'],
  ['physicalViolence', 'whacks you with the newspaper'],
  ['physicalViolence', 'Blows you up'],

  // tier9_userState
  ['userVenting', 'god im so tired'],
  ['userVenting', 'oougghhhh'],
  ['userVenting', 'OTL'],
  ['userVenting', 'im :tennadead:'],
  ['userVenting', 'i am dead'],
  ['userVenting', 'i have had a really long day'],
  ['userVenting', 'what a dogshit day'],
  ['userHelpPain', "take my cramps and i'll forgive you"],
  ['userHelpPain', "Can I give you my cramps I'm in pain rn"],
  ['userHelpPain', 'i need ibuprofen'],
  ['userHelpPain', "I'm in so much painnnn"],
  ['userHelpPain', "I'm in so much paaaaain"],
  ['userHelpPain', 'help tenna everything hurts'],
  ['userHelpPain', 'my body horts'],
  ['userHelpPain', 'im in pain'],
  ['userHelpPain', 'my headache is killing me'],
  ['userHelpPain', 'my tummy hurts :<'],
  ['userHelp', 'heeeelp'],
  ['userHelp', 'she needs help'],
  ['userHelp', 'please help ;;'],
  ['userHelp', 'help pls'],
  ['userFeelingGood', "I'm feeling good today, Tenna!"],
  ['userFeelingGood', 'im feelin alright'],
  ['userFeelingGood', 'i am okay'],
  ['userFeelingGood', 'im good'],
  ['userFeelingGood', 'I feel pretty awesome actually'],
  ['userFeelingGood', 'Im doing a bit better'],
  ['userFeelingGood', 'i ok :)'],
  ['userFeelingGood', 'i am ALL GOOD'],
  ['userFeelingBad', 'i am NOT feeling good'],
  ['userFeelingBad', 'I am feeling NOT good'],
  ['userFeelingBad', 'i feel bad'],
  ['userFeelingBad', 'im glooby'],
  ['userFeelingBad', "I'm doin awful"],
  ['userFeelingBad', 'i am feeling so lousy'],
  ['userFeelingBad', "I'm feeling like shit"],
  ['userFeelingBad', 'i feel like crap'],
  ['userFeelingBad', 'i am depressed'],
  ['userFeelingBad', 'I AM MAD'],
  ['userFeelingBad', 'i am a little sad'],
  ['userDayGood', 'i am having an amazing day'],
  ['userDayGood', "my day's been FUCKIN AWESOME"],
  ['userDayGood', "Today's been good!!"],
  ['userDayGood', 'having a wonderful day'],
  ['userDayGood', 'my day is really great'],
  ['userDayGood', 'his day was fun'],
  ['userDayGood', 'their today is so nice'],
  ['userDayGood', 'my day has been fine'],
  ['userDayGood', "today's been pretty fuckin amazing"],
  ['userDayBad', 'having a bad day'],
  ['userDayBad', 'my day has been crappy'],
  ['userDayBad', "today's been pretty fuckin horrible"],
  ['userDayBad', 'today is not good'],

  // tier10_selfQuestions
  ['selfQuestionBotUpdate', "y'know what, let's do a dialogue update this weekend"],
  ['selfQuestionBotUpdate', 'ready for a new feature update?'],
  ['selfQuestionBotUpdate', 'I need to update your code, bud'],
  ['selfQuestionBotUpdate', 'we gotta add some more to your dialogue soon'],
  ['selfQuestionBotLobotomy', 'time for a lobotomy'],
  ['selfQuestionBotLobotomy', 'do you want another lobotomy'],
  ['selfQuestionBotLobotomy', 'do you want me to rewire you again'],
  ['selfQuestionBotLobotomy', "I'm going to lobotomize your brain if you don't stop"],
  ['selfQuestionBotLobotomy', "It's Lobotomy Time"],
  ['selfQuestionBotLobotomy', "is lobotomy time, yes"],
  ['selfQuestionWhy', 'why are you like this'],
  ['selfQuestionWhy', 'why must you be like this'],
  ['selfQuestionWhy', 'why cant you understand me???'],
  ['selfQuestionWhy', 'why would you hurt me'],
  ['selfQuestionWhy', "why don't you hit the bricks"],
  ['selfQuestionWhy', 'whyyyyy tenna'],
  ['selfQuestionWhy', 'tenna why, just why'],
  ['selfQuestionCanYou', 'could you please stop'],
  ['selfQuestionCanYou', 'can you do a trick?'],
  ['selfQuestionCanYou', 'are you able to hang out later?'],
  ['selfQuestionCanYou', 'are you gonna chill out'],
  ['selfQuestionWho', 'who are you??'],
  ['selfQuestionWho', 'who even are you'],
  ['selfQuestionWho', 'who is tenna??'],
  ['selfQuestionWho', "who's this guy?"],
  ['selfQuestionWho', "who're you"],
  ['selfQuestionWho', 'who the fuck is this guy'],
  ['selfQuestionHow', 'are you okay??'],
  ['selfQuestionHow', 'how you doin'],
  ['selfQuestionHow', 'r u ok'],
  ['selfQuestionHow', 'how is it going'],
  ['selfQuestionHow', 'how it going'],
  ['selfQuestionHow', "how's it hangin"],
  ['selfQuestionHow', 'how art thou'],
  ['selfQuestionHow', 'is your day going okay?'],
  ['selfQuestionHow', 'has your day been good?'],
  ['selfQuestionHow', 'how was your day?'],
  ['selfQuestionHow', 'how r ya'],
  ['selfQuestionHow', 'are u alright'],
  ['selfQuestionHow', 'are you doing alright'],
  ['selfQuestionWhatsUp', 'what is going on'],
  ['selfQuestionWhatsUp', "what's happening"],
  ['selfQuestionWhatsUp', 'what is happenin'],
  ['selfQuestionWhatsUp', 'what is going down'],
  ['selfQuestionWhatsUp', 'wassup'],
  ['selfQuestionWhatsUp', 'waaaasssuuuup'],
  ['selfQuestionWhatsUp', 'wazzuup'],
  ['selfQuestionWhatsUp', 'watcha doin'],
  ['selfQuestionWhatsUp', "what're you up to"],
  ['selfQuestionWhatsUp', 'sup'],
  ['selfQuestionWhat', 'what even are you'],
  ['selfQuestionWhat', 'what the fuck is tenna'],
  ['selfQuestionWhat', 'what is a tenna'],
  ['selfQuestionWhat', 'what do you even do'],
  ['selfQuestionWhat', 'what are you'],
  ['selfQuestionWhat', 'what the hell are you'],
  ['selfQuestionOpinion', 'how do you respond to the allegations'],
  ['selfQuestionOpinion', 'what do you think about'],
  ['selfQuestionOpinion', 'how do you feel about this'],
  ['selfQuestionOpinion', 'what is your take on'],
  ['selfQuestionOpinion', "what's your opinion"],
  ['selfQuestionOpinion', 'what would you say about'],
  ['selfQuestionOpinion', 'how do you react to'],
  ['selfQuestionWhere', 'where are you'],
  ['selfQuestionWhere', 'where r you'],
  ['selfQuestionWhere', 'where are you at'],
  ['selfQuestionWhere', 'where do you live'],
  ['selfQuestionWhere', 'where you at'],
  ['selfQuestionWhere', 'where are you staying'],
  ['selfQuestionWhere', 'where is tenna'],
  ['selfQuestionWhere', 'where do you come from'],
  
  // tier11_tvQuestions
  ['tvQuestionWhen', 'when is the next show?'],
  ['tvQuestionWhen', 'what time is the next episode'],
  ['tvQuestionWhen', "when's the broadcast???"],
  ['tvQuestionWhen', 'when is tv time'],
  ['tvQuestionWhen', 'WHEN TV TIME, TENNA'],
  ['tvQuestionWhen', 'what time are you on air'],
  ['tvQuestionWhen', 'when do you go on air?'],
  ['tvQuestionRating', 'how are the ratings?'],
  ['tvQuestionRating', 'are ratings low?'],
  ['tvQuestionRating', 'are you popular?'],
  ['tvQuestionRating', 'how many fans do you have??'],
  ['tvQuestionRating', 'how well is the show going?'],
  ['tvQuestionRating', 'do you get a lot of viewers?'],
  ['tvQuestionRating', 'how is tv time'],
  ['tvQuestionWhat', 'What show do you host again?'],
  ['tvQuestionWhat', 'what is the name of your show'],
  ['tvQuestionWhat', 'which channel is your show on?'],
  ['tvQuestionWhat', 'what channel is tv time on'],
  ['tvQuestionWhat', 'what is your channel??'],
  ['tvQuestionWhat', 'which program should I watch?'],
  ['tvQuestionHow', 'how do I watch tv time??'],
  ['tvQuestionHow', 'how can I tune in'],
  ['tvQuestionHow', 'how can I find you'],
  ['tvQuestionHow', 'how watch'],
  ['tvQuestionHow', 'how do I see your show tenna??'],

  // tier12_greetings
  ['goodMorning', 'good morning!!'],
  ['goodMorning', 'morning tenna!!'],
  ['goodMorning', "g'morning tenna"],
  ['goodMorning', 'morning'],
  ['goodMorning', "mornin'"],
  ['goodMorning', 'morning'],
  ['goodMorning', 'gm'],
  ['goodMorning', 'rise and shine tenna!'],
  ['goodnight', 'nighty night'],
  ['goodnight', 'good night'],
  ['goodnight', "g'night tenna!"],
  ['goodnight', 'nighttttt'],
  ['goodnight', 'niiiiight'],
  ['goodnight', 'sleep tight tenna!'],
  ['goodnight', 'have a good night tenna!'],
  ['goodnight', 'night night!'],
  ['goodnight', 'nini!'],
  ['goodbye', 'byeee tennaaaa'],
  ['goodbye', 'byyyeee'],
  ['goodbye', 'good bye'],
  ['goodbye', 'goodbye'],
  ['goodbye', 'seeyaa'],
  ['goodbye', 'bye byeee'],
  ['greeting', 'Hi Tenna!!'],
  ['greeting', 'Hello'],
  ['greeting', 'Yoooo Tenna!!!'],
  ['greeting', 'yo'],
  ['greeting', 'heyyyyyaa'],
  ['greeting', 'Heyyyy'],
  ['greeting', 'Heyy, babygirl :too_silly:'],
  ['greeting', 'hiiii mr tenna'],
  ['greeting', 'hewwo'],

  // tier13_emotes
  ['haterMention', ':spampog:'],
  ['queenMention', ':queenlmao:'],
  ['whoMention', ':fellpipis:'],
  ['whoMention', ':whuh_dfn:'],
  ['tennaEmotePositive', ':tennalol:'],
  ['tennaEmotePositive', ':tenna_Whisper:'],
  ['tennaEmoteNegative', ':tennaevil:'],
  ['tennaEmoteNegative', ':whuh:']
]

describe('Dialogue Handler Tests', () => {
  for (const content of examples) {
    it(`should correctly detect "${content[1]}" as ${content[0]}`, () => {
      expect(handler.detectIntent(content[1])).toBe(content[0]);
    });
  }
});