 const handler = require('../../src/features/conversation/handler.js'); 
const examples = [
  // empty
  ['empty', ''],

  // fallback
  ['fallback', 'sdkfjdshfsd'],
  ['fallback', 'lalalalalalala'],

  // tier1_blockers
  ['offLimits', 'wireplay'],
  ['offLimits', 'slaps ur boner'],

  // tier2_questionsToTenna
  ['askTennaAwake', 'are you up'],
  ['askTennaAwake', 'you awake?'],
  ['askTennaAwake', 'are u there'],
  ['askTennaAwake', 'are you here???'],
  ['askTennaGoodBoy', 'who is a good boy'],
  ['askTennaGoodBoy', "who's a good boy???"],
  ['askTennaGoodBoy', 'good boy!!'],
  ['askTennaGoodBoy', 'who is a good tv'],
  ['askTennaLikeGender', 'are you into dudes?'],
  ['askTennaLikeGender', 'do you like enbies??'],
  ['askTennaLikeGender', 'you into women?'],
  ['askTennaLikeGender', 'you like boys?'],
  ['askTennaFlirt', 'do you have a boyfriend?'],
  ['askTennaFlirt', 'got a gf?'],
  ['askTennaFlirt', 'do you wanna go out?'],
  ['askTennaFlirt', 'wanna date me??'],
  ['askTennaFlirt', 'touches your nose'],
  ['askTennaFlirt', 'gropes your dials'],
  ['askTennaFlirt', 'kiss me!!!'],
  ['askTennaFlirt', 'can you kiss me'],
  ['askTennaFlirt', 'licking your screen'],
  ['askTennaFlirt', 'are you interested in anyone?'],
  ['askTennaFlirt', 'are you taken'],
  ['askTennaFlirt', 'will you marry me?'],
  ['askTennaFlirt', 'do you have a crush on someone?'],
  ['askTennaFlirt', 'do you like someone?'],
  ['askTennaFlirt', 'are you seeing anyone?'],
  ['askTennaFlirt', 'caress your buttons'],
  ['askTennaFlirt', 'wanna be my boyfriend?'],
  ['askTennaLove', 'do you love me?'],
  ['askTennaLove', 'do you love your fans'],
  ['askTennaLove', "don't you love your show??"],
  ['askTennaLove', 'you love tv'],
  ['askTennaLove', 'you love your fans, dont u'],
  ['askTennaLove', 'do u rly love television'],
  ['askTennaLove', 'do you love your job???'],
  ['askTennaAge', 'what year were u born??'],
  ['askTennaAge', 'what is your age'],
  ['askTennaAge', "what's your age"],
  ['askTennaAge', 'how old ARE you'],
  ['askTennaAge', 'how old r u'],
  ['askTennaAge', 'are you old'],
  ['askTennaAge', 'what year were u born'],
  ['askTennaAge', 'how old is tenna?'],
  ['askTennaAge', 'is tenna old?'],
  ['askTennaRemember', 'do you remember the time when'],
  ['askTennaRemember', 'you remember, right?'],
  ['askTennaRemember', 'dont u remember me'],
  ['askTennaRemember', 'can you remember that?'],
  ['askTennaRemember', 'did you forget about me'],
  ['askTennaRemember', 'remember when that happened?'],
  ['askTennaKnow', 'what do you know about this?'],
  ['askTennaKnow', 'have you learned about discord?'],
  ['askTennaKnow', 'what do you hear about me'],
  ['askTennaKnow', 'have you heard about'],
  ['askTennaKnow', 'ever hear of'],
  ['askTennaKnow', 'have you heard who'],
  ['askTennaKnow', 'did you hear about anything'],
  ['askTennaKnow', 'did u hear anything'],
  ['askTennaKnow', 'what do you know of deltarune'],

  // tier3_commands
  ['quizCommand', 'give me a quiz'],
  ['quizCommand', 'can I have a quiz'],
  ['quizCommand', 'do a quiz'],
  ['quizCommand', 'give quiz'],
  ['quizCommand', 'quiz them'],
  ['quizCommand', 'quiz me!!!'],
  ['quizCommand', 'want a quiz'],
  ['quizCommand', 'quiz her NOW'],
  ['quizCommand', 'tenna can I do a quiz'],
  ['quizCommand', 'can I try quiz'],
  ['balanceCommand', 'how much do they have'],
  ['balanceCommand', 'where are my points'],
  ['balanceCommand', 'how many points do I have??'],
  ['balanceCommand', 'how many do I have'],
  ['balanceCommand', 'what is my balance'],
  ['balanceCommand', 'what is my points balance'],
  ['balanceCommand', 'show my points'],
  ['introduceCommand', 'my name is'],
  ['introduceCommand', 'my birthday is'],
  ['introduceCommand', 'my pronouns are'],
  ['introduceCommand', 'my nickname is'],
  ['introduceCommand', 'I want to introduce myself'],
  ['introduceCommand', 'want to know my name?'],
  ['introduceCommand', 'wanna learn my birthday?'],
  ['introduceCommand', 'wanna hear my nickname?'],
  ['scheduleCommand', 'schedule an event please!'],
  ['scheduleCommand', 'tenna can you make a watch party for us'],
  ['scheduleCommand', 'tenna can you make a writing sprint for us'],
  ['scheduleCommand', 'start the event'],
  ['scheduleCommand', 'plan a party for meeee'],
  ['scheduleCommand', 'set my party!!'],
  ['scheduleCommand', 'create an event tenna!!'],

  // tier4_conversational
  ['tennaQuoteTVTime', 'what time is it??'],
  ['tennaQuoteTVTime', 'its TV TIME!!!'],
  ['tennaQuoteTVTime', "It's T! V! TIME!"],
  ['tennaQuoteTVTime', 'say it with him folks!!'],
  ['tennaQuoteJuice', 'turn up the juice! turn up the juice!!!'],
  ['tennaQuoteJuice', 'fresh from the juice!!!'],
  ['tennaQuoteKillThisGuy', 'how do I kill this guy?'],
  ['tennaQuoteKillThisGuy', 'kill tenna NOW'],
  ['tennaQuoteKillThisGuy', 'how do we kill this guy'],
  ['tennaQuoteDial', 'dont touch that dial!'],
  ['tennaQuoteFamilyFight', 'the family is fighting again'],
  ['tennaQuoteFamilyFight', "family's fighting again"],
  ['saySorry', 'knock it off Tenna'],
  ['saySorry', 'BE NICE'],
  ['saySorry', 'say your sorry NOW'],
  ['saySorry', 'tenna quit it'],
  ['saySorry', 'stop that'],
  ['saySorry', 'can you say something nice'],
  ['saySorry', 'say psyche right now'],
  ['saySorry', "I'm so mad at you rn"],
  ['saySorry', "they're so mad at you"],
  ['saySorry', "say you're sorry"],
  ['saySorry', 'apologize to them!!'],
  ['saySorry', 'say something nicer to me'],
  ['saySorry', 'say you didnt mean it.....'],
  ['saySorry', "don't be mean"],
  ['imSorry', 'IM SO SOWWY TENNAAAA'],
  ['imSorry', "I'm so fucking sorry tenna"],
  ['imSorry', 'i am sorry'],
  ['imSorry', 'please forgive me'],
  ['imSorry', 'FORGIVE HER PLEASEEE'],
  ['imSorry', 'forgiiiiive meeeeeee'],
  ['imSorry', 'im sowwwwyyyyy'],
  ['imSorry', 'sorry tenna...'],
  ['dontWorry', "don't worry about it!"],
  ['dontWorry', "Don’t worry about it :3"],
  ['dontWorry', 'no worries kitten'],
  ['dontWorry', 'eh forget about it'],
  ['dontWorry', 'ignore them, tenna'],
  ['dontWorry', 'forget that'],
  ['dontWorry', 'its all good'],
  ['dontWorry', "it's all right!"],
  ['dontWorry', 'its all okay'],
  ['dontWorry', 'do not worry my silly little tv'],
  ['dontWorry', 'ignore me okay'],
  ['youllSee', 'oh youll find out'],
  ['youllSee', "you'll see soon...."],
  ['youllSee', 'you will'],
  ['youllSee', 'you will seeeee'],
  ['youllSee', 'youuuu willlll'],
  ['getYou', 'IM GONNA GET YOU!!!!'],
  ['getYou', 'me when i fucking get you'],
  ['getYou', "I'm going to fucking get you"],
  ['getYou', 'dont make me get you'],
  ['getYou', "I'm gonna get your ass"],
  ['getYou', 'when I get my hands on you!!!'],
  ['getYou', 'ONCE I GET A HOLD OF YOU'],
  ['thankYou', 'thank you tennaaaa'],
  ['thankYou', 'Thanks babe'],
  ['thankYou', 'big thank'],
  ['thankYou', 'thanks tenna!!!!'],
  ['thankYou', 'Great! Thanks for your patience during testing, Tenna!'],
  ['thankYou', 'thaaaaaanks tenna!!!!'],
  ['thankYou', 'ty'],
  ['thankYou', 'I said thank you, idiot'],
  ['bark', 'your a puppy'],
  ['bark', "You're a doggo"],
  ['bark', 'youre a silly pup'],
  ['bark', 'walkies?'],
  ['bark', 'i demand that you bark for us'],
  ['bark', 'command you to bark'],
  ['bark', 'BARK FOR ME'],
  ['bark', 'bark NOW'],
  ['bark', 'bark RIGHT NOW!!!'],

  // tier5_characters
  ['spamtonMention', 'do you miss your ex partner?'],
  ['spamtonMention', 'do you miss your ex?'],
  ['spamtonMention', 'where is the email guy?'],
  ['spamtonMention', 'spammy'],
  ['mikeMention', 'mike!!!'],
  ['pipisMention', 'pipis????'],
  ['susieMention', 'do you like snoozie?'],
  ['ralseiMention', 'who is ralsei'],
  ['torielMention', 'do you like Tori?'],
  ['familyMention', 'where is dess'],
  ['knightMention', 'what can you say about the knight'],
  ['queenMention', 'queenie beenie'],
  ['lancerMention', 'lancer'],
  ['kingMention', 'why did you call him kingy doodle'],
  ['mettatonMention', 'would you go out with mettaton'],
  ['laninoElninaMention', 'lanino!'],
  ['laninoElninaMention', 'elnina!'],
  ['laninoElninaMention', 'the weather duo!'],
  ['workersMention', 'do you pay battat enough'],
  ['workersMention', 'WHERE IS MY LITTLE PLUEY'],
  ['whoMention', 'rouxls'],
  ['whoMention', 'Do you like Toby Fox'],

  // tier6_otherMentions
  ['emailMention', 'what is an e-mail?'],
  ['mikuMention', 'Would you duet with Miku??'],
  ['mikuMention', 'do you like Vocaloid?'],
  ['discordMention', 'having fun in this server?'],
  ['discordMention', 'how did you learn discord'],
  ['discordMention', 'who taught you the internet'],
  ['discordMention', 'how did you get online?'],
  ['beingBotMention', 'wait are you ai'],
  ['beingBotMention', 'are you a chat bot'],
  ['beingBotMention', "aren't you a chat bot"],
  ['beingBotMention', 'u r bot'],
  ['beingBotMention', 'your a computer program'],
  ['beingBotMention', 'are you real'],

  // tier7_compliments
  ['loveFans', 'can you say you love your fans'],
  ['loveFans', 'will you say you love us?'],
  ['loveFans', 'would you say you love your fans?'],
  ['loveFans', 'can you say you love me'],
  ['loveFans', 'can you say that you love me'],
  ['loveFans', 'do you love fans'],
  ['hugFans', 'tenna can you hug me'],
  ['hugFans', 'tenna can I get a hug?'],
  ['hugFans', 'could you hug me?'],
  ['hugFans', 'could I have a hug?'],
  ['hugFans', 'could you give me a hug?'],
  ['hugFans', 'could I get a sloppy kiss?'],
  ['hugFans', 'will you pat me'],
  ['hugFans', 'HUG THEM NOW'],
  ['hugFans', 'JAY NEEDS A HUG PLEASE'],
  ['hugFans', 'could I get some love?'],
  ['hugFans', 'kiss pls'],
  ['compliment', 'I love you'],
  ['compliment', 'we LOVE TV!!!'],
  ['compliment', 'i fucking love tenna'],
  ['compliment', 'you are SO CUTIEFUL'],
  ['compliment', 'your hot'],
  ['compliment', "you're so handsome!"],
  ['compliment', 'ur hot'],
  ['compliment', 'you look so cute'],
  ['compliment', 'you are a funny man'],
  ['compliment', 'ilovetv'],
  ['compliment', 'I LOVE WATCHING TV'],
  ['physicalAffection', 'kisses you'],
  ['physicalAffection', 'hugs you'],
  ['physicalAffection', 'im smooching u'],
  ['physicalAffection', 'pats your nose'],
  ['physicalAffection', 'cuddle tenna'],
  ['physicalAffection', 'slaps your ass'],
  ['physicalAffection', 'slapping ur booty'],

  // tier8_insults
  ['insultBoo', 'BOO YOU SUCK'],
  ['insultBoo', 'BOOO'],
  ['insultBoo', 'booooo stinky'],
  ['insultBoo', 'BOO UR BORING'],
  ['insultBoo', 'GET OFF THE STAGE'],
  ['insultOld', 'you are SO OLD'],
  ['insultOld', 'you are an old tv!!'],
  ['insultOld', "you're ancient!!!"],
  ['insultOld', "OLD MAN"],
  ['insultOld', "god ur old"],
  ['insultOld', "u r a boomer"],
  ['insultOld', "okay boomer"],
  ['insultOld', "you an old bitch"],
  ['insultShutUp', 'dude, shut up'],
  ['insultShutUp', 'shut the FUCK UP!!!'],
  ['insultShutUp', 'leave me alone'],
  ['insultShutUp', 'who asked'],
  ['insultShutUp', 'stop bitching'],
  ['insultShutUp', 'what are u yapping about'],
  ['insultShutUp', 'please be quiet'],
  ['insult', 'you are an idiot'],
  ['insult', 'you suck'],
  ['insult', 'you a BITCH'],
  ['insult', 'ur a meanie!!!'],
  ['insult', "god you're stupid"],
  ['insult', "you're lame and annoying"],
  ['insult', "u r so rude"],
  ['insult', "kill urself mr tenna"],
  ['insult', "KILLS YOU WITH MY MIND!!!"],
  ['insult', "TRASH HEAP!!!"],
  ['insult', ":tennafuckyou:"],
  ['physicalViolence', 'bites you'],
  ['physicalViolence', 'kicks your shins'],
  ['physicalViolence', 'punches your screen'],
  ['physicalViolence', 'BEATING YOU UP'],
  ['physicalViolence', 'throwing you down the stairs'],
  ['physicalViolence', 'ripping off your nose'],
  ['physicalViolence', 'shocking tenna'],
  ['physicalViolence', 'steals your debit card'],

  // tier9_userState
  ['userVenting', 'god im so tired'],
  ['userVenting', 'oougghhhh'],
  ['userVenting', 'OTL'],
  ['userVenting', 'im :tennadead:'],
  ['userVenting', 'i am dead'],
  ['userVenting', 'i have had a really long day'],
  ['userVenting', 'what a dogshit day'],
  ['userHelp', 'heeeelp'],
  ['userHelp', 'she needs help'],
  ['userHelp', 'please help ;;'],
  ['userHelp', 'help pls'],
  ['userFeelingGood', "I'm feeling good today, Tenna!"],
  ['userFeelingGood', 'im feelin alright'],
  ['userFeelingGood', 'i am okay'],
  ['userFeelingGood', 'im good'],
  ['userFeelingGood', 'I feel pretty awesome actually'],
  ['userFeelingGood', 'Im doing a bit better'],
  ['userFeelingGood', 'i ok :)'],
  ['userFeelingGood', 'i am ALL GOOD'],
  ['userFeelingBad', 'i am NOT feeling good'],
  ['userFeelingBad', 'I am feeling NOT good'],
  ['userFeelingBad', 'i feel bad'],
  ['userFeelingBad', 'im glooby'],
  ['userFeelingBad', "I'm doin awful"],
  ['userFeelingBad', 'i am feeling so lousy'],
  ['userFeelingBad', "I'm feeling like shit"],
  ['userFeelingBad', 'i feel like crap'],
  ['userFeelingBad', 'i am depressed'],
  ['userFeelingBad', 'I AM MAD'],
  ['userFeelingBad', 'i am a little sad'],
  ['userDayGood', 'i am having an amazing day'],
  ['userDayGood', "my day's been FUCKIN AWESOME"],
  ['userDayGood', "Today's been good!!"],
  ['userDayGood', 'having a wonderful day'],
  ['userDayGood', 'my day is really great'],
  ['userDayGood', 'his day was fun'],
  ['userDayGood', 'their today is so nice'],
  ['userDayGood', 'my day has been fine'],
  ['userDayGood', "today's been pretty fuckin amazing"],
  ['userDayBad', 'having a bad day'],
  ['userDayBad', 'my day has been crappy'],
  ['userDayBad', "today's been pretty fuckin horrible"],
  ['userDayBad', 'today is not good'],

  // tier10_selfQuestions
  ['selfQuestionWhy', 'why are you like this'],
  ['selfQuestionWhy', 'why must you be like this'],
  ['selfQuestionWhy', 'why cant you understand me???'],
  ['selfQuestionWhy', 'why would you hurt me'],
  ['selfQuestionWhy', "why don't you hit the bricks"],
  ['selfQuestionWhy', 'whyyyyy tenna'],
  ['selfQuestionWhy', 'tenna why, just why'],
  ['selfQuestionCanYou', 'could you please stop'],
  ['selfQuestionCanYou', 'can you do a trick?'],
  ['selfQuestionCanYou', 'are you able to hang out later?'],
  ['selfQuestionCanYou', 'are you gonna chill out'],
  ['selfQuestionWho', 'who are you??'],
  ['selfQuestionWho', 'who even are you'],
  ['selfQuestionWho', 'who is tenna??'],
  ['selfQuestionWho', "who's this guy?"],
  ['selfQuestionWho', "who're you"],
  ['selfQuestionWho', 'who the fuck is this guy'],
  ['selfQuestionHow', 'are you okay??'],
  ['selfQuestionHow', 'how you doin'],
  ['selfQuestionHow', 'r u ok'],
  ['selfQuestionHow', 'how is it going'],
  ['selfQuestionHow', 'how it going'],
  ['selfQuestionHow', "how's it hangin"],
  ['selfQuestionHow', 'how art thou'],
  ['selfQuestionHow', 'is your day going okay?'],
  ['selfQuestionHow', 'has your day been good?'],
  ['selfQuestionHow', 'how was your day?'],
  ['selfQuestionHow', 'how r ya'],
  ['selfQuestionHow', 'are u alright'],
  ['selfQuestionHow', 'are you doing alright'],
  ['selfQuestionWhatsUp', 'what is going on'],
  ['selfQuestionWhatsUp', "what's happening"],
  ['selfQuestionWhatsUp', 'what is happenin'],
  ['selfQuestionWhatsUp', 'what is going down'],
  ['selfQuestionWhatsUp', 'wassup'],
  ['selfQuestionWhatsUp', 'waaaasssuuuup'],
  ['selfQuestionWhatsUp', 'wazzuup'],
  ['selfQuestionWhatsUp', 'watcha doin'],
  ['selfQuestionWhatsUp', "what're you up to"],
  ['selfQuestionWhatsUp', 'sup'],
  ['selfQuestionWhat', 'what even are you'],
  ['selfQuestionWhat', 'what the fuck is tenna'],
  ['selfQuestionWhat', 'what is a tenna'],
  ['selfQuestionWhat', 'what do you even do'],
  ['selfQuestionWhat', 'what are you'],
  ['selfQuestionWhat', 'what the hell are you'],
  ['selfQuestionOpinion', 'how do you respond to the allegations'],
  ['selfQuestionOpinion', 'what do you think about'],
  ['selfQuestionOpinion', 'how do you feel about this'],
  ['selfQuestionOpinion', 'what is your take on'],
  ['selfQuestionOpinion', "what's your opinion"],
  ['selfQuestionOpinion', 'what would you say about'],
  ['selfQuestionOpinion', 'how do you react to'],
  ['selfQuestionWhere', 'where are you'],
  ['selfQuestionWhere', 'where r you'],
  ['selfQuestionWhere', 'where are you at'],
  ['selfQuestionWhere', 'where do you live'],
  ['selfQuestionWhere', 'where you at'],
  ['selfQuestionWhere', 'where are you staying'],
  ['selfQuestionWhere', 'where is tenna'],
  ['selfQuestionWhere', 'where do you come from'],
  
  // tier11_tvQuestions
  ['tvQuestionWhen', 'when is the next show?'],
  ['tvQuestionWhen', 'what time is the next episode'],
  ['tvQuestionWhen', "when's the broadcast???"],
  ['tvQuestionWhen', 'when is tv time'],
  ['tvQuestionWhen', 'WHEN TV TIME, TENNA'],
  ['tvQuestionWhen', 'what time are you on air'],
  ['tvQuestionWhen', 'when do you go on air?'],
  ['tvQuestionRating', 'how are the ratings?'],
  ['tvQuestionRating', 'are ratings low?'],
  ['tvQuestionRating', 'are you popular?'],
  ['tvQuestionRating', 'how many fans do you have??'],
  ['tvQuestionRating', 'how well is the show going?'],
  ['tvQuestionRating', 'do you get a lot of viewers?'],
  ['tvQuestionRating', 'how is tv time'],
  ['tvQuestionWhat', 'What show do you host again?'],
  ['tvQuestionWhat', 'what is the name of your show'],
  ['tvQuestionWhat', 'which channel is your show on?'],
  ['tvQuestionWhat', 'what channel is tv time on'],
  ['tvQuestionWhat', 'what is your channel??'],
  ['tvQuestionWhat', 'which program should I watch?'],
  ['tvQuestionHow', 'how do I watch tv time??'],
  ['tvQuestionHow', 'how can I tune in'],
  ['tvQuestionHow', 'how can I find you'],
  ['tvQuestionHow', 'how watch'],
  ['tvQuestionHow', 'how do I see your show tenna??'],

  // tier12_greetings
  ['goodMorning', 'good morning!!'],
  ['goodMorning', 'morning tenna!!'],
  ['goodMorning', "g'morning tenna"],
  ['goodMorning', 'morning'],
  ['goodMorning', "mornin'"],
  ['goodMorning', 'morning'],
  ['goodMorning', 'gm'],
  ['goodMorning', 'rise and shine tenna!'],
  ['goodnight', 'nighty night'],
  ['goodnight', 'good night'],
  ['goodnight', "g'night tenna!"],
  ['goodnight', 'nighttttt'],
  ['goodnight', 'niiiiight'],
  ['goodnight', 'sleep tight tenna!'],
  ['goodnight', 'have a good night tenna!'],
  ['goodnight', 'night night!'],
  ['goodnight', 'nini!'],
  ['goodbye', 'byeee tennaaaa'],
  ['goodbye', 'byyyeee'],
  ['goodbye', 'good bye'],
  ['goodbye', 'goodbye'],
  ['goodbye', 'seeyaa'],
  ['goodbye', 'bye byeee'],
  ['greeting', 'Hi Tenna!!'],
  ['greeting', 'Hello'],
  ['greeting', 'Yoooo Tenna!!!'],
  ['greeting', 'yo'],
  ['greeting', 'heyyyyyaa'],
  ['greeting', 'Heyyyy'],
  ['greeting', 'Heyy, babygirl :too_silly:'],
  ['greeting', 'hiiii mr tenna'],
  ['greeting', 'hewwo'],

  // tier13_emotes
  ['haterMention', ':spampog:'],
  ['queenMention', ':queenlmao:'],
  ['whoMention', ':fellpipis:'],
  ['whoMention', ':whuh_dfn:'],
  ['tennaEmotePositive', ':tennalol:'],
  ['tennaEmotePositive', ':tenna_Whisper:'],
  ['tennaEmoteNegative', ':tennaevil:'],
  ['tennaEmoteNegative', ':whuh:']
]

describe('Dialogue Handler Tests', () => {
  for (const content of examples) {
    it(`should correctly detect "${content[1]}" as ${content[0]}`, () => {
      expect(handler.detectIntent(content[1])).toBe(content[0]);
    });
  }
});